<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>06--Chapter-5.knit</title>

<script src="site_libs/header-attrs-2.10/header-attrs.js"></script>
<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cosmo.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>





<link rel="stylesheet" href="style.css" type="text/css" />



<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.tab('show');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Cedric's Projects</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">About</a>
</li>
<li>
  <a href="Summer-Research-2018-Markdown.html">Proj.1 (R)</a>
</li>
<li>
  <a href="pokemon-project-2020.html">Proj.2 (R)</a>
</li>
<li>
  <a href="gendered_education_project_complete.html">Proj.3 (R)</a>
</li>
<li>
  <a href="https://larylc.github.io/chess_birthday_project/">Proj.4 (R &amp; Python)</a>
</li>
<li>
  <a href="https://loganlary.shinyapps.io/anime1_030521/?_ga=2.199251374.1633841057.1615147342-569369622.1613318148">Minor Proj.1 (R)</a>
</li>
<li>
  <a href="tvanalysis.html">Minor Proj.2 (Python)</a>
</li>
<li>
  <a href="missing_chess_records.html">Minor Proj.3 (R &amp; Python)</a>
</li>
<li>
  <a href="https://loganlary.shinyapps.io/prodigies_app/?_ga=2.15136438.103236738.1633010249-569369622.1613318148">Data Viz App (R)</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">




</div>


<div id="task-14-which-stats-are-most-useful-for-predicting-legendary-sub-legendary-mythical-status" class="section level2">
<h2>Task 14: Which stat(s) are most useful for predicting legendary/ sub-legendary/ mythical status?</h2>
<p>Let’s first build the necessary data frame for analysis:</p>
<pre class="r"><code>predict_special&lt;- data.frame(pokemon_data_full[,c(10,7,18:24)])


predict_special&lt;- data.frame(predict_special[predict_special$type != &quot;&quot;,])
str(predict_special)</code></pre>
<pre><code>## &#39;data.frame&#39;:    1028 obs. of  9 variables:
##  $ type_1      : chr  &quot;Grass&quot; &quot;Grass&quot; &quot;Grass&quot; &quot;Grass&quot; ...
##  $ status      : chr  &quot;Normal&quot; &quot;Normal&quot; &quot;Normal&quot; &quot;Normal&quot; ...
##  $ total_points: int  318 405 525 625 309 405 534 634 634 314 ...
##  $ hp          : int  45 60 80 80 39 58 78 78 78 44 ...
##  $ attack      : int  49 62 82 100 52 64 84 130 104 48 ...
##  $ defense     : int  49 63 83 123 43 58 78 111 78 65 ...
##  $ sp_attack   : int  65 80 100 122 60 80 109 130 159 50 ...
##  $ sp_defense  : int  65 80 100 120 50 65 85 85 115 64 ...
##  $ speed       : int  45 60 80 80 65 80 100 100 100 43 ...</code></pre>
<pre class="r"><code>predict_legendary &lt;- mutate(predict_special,
                            status = ifelse(status == &quot;Legendary&quot;, 1, 0))
table(predict_legendary$status)</code></pre>
<pre><code>## 
##   0   1 
## 989  39</code></pre>
<pre class="r"><code>predict_sublegendary&lt;- mutate(predict_special,
                            status = ifelse(status == &quot;Sub Legendary&quot;, 1, 0))
table(predict_sublegendary$status)</code></pre>
<pre><code>## 
##   0   1 
## 983  45</code></pre>
<pre class="r"><code>predict_mythical&lt;-mutate(predict_special,
                            status = ifelse(status == &quot;Mythical&quot;, 1, 0))
table(predict_mythical$status)</code></pre>
<pre><code>## 
##   0   1 
## 999  29</code></pre>
<p>Now, that we have the data frames, we can proceed to building the model:</p>
<pre class="r"><code>predict_legendary_fit &lt;- glm(status ~ attack + defense + sp_attack + sp_defense + hp + speed, family = binomial, data = predict_legendary)
summary(predict_legendary_fit)</code></pre>
<pre><code>## 
## Call:
## glm(formula = status ~ attack + defense + sp_attack + sp_defense + 
##     hp + speed, family = binomial, data = predict_legendary)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -1.9148  -0.1046  -0.0393  -0.0062   5.3132  
## 
## Coefficients:
##               Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept) -20.495902   2.325900  -8.812  &lt; 2e-16 ***
## attack        0.018577   0.008039   2.311 0.020840 *  
## defense       0.030676   0.009628   3.186 0.001443 ** 
## sp_attack     0.026460   0.007777   3.402 0.000669 ***
## sp_defense    0.030537   0.010044   3.040 0.002364 ** 
## hp            0.046214   0.007992   5.782 7.36e-09 ***
## speed         0.032161   0.009667   3.327 0.000878 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 331.70  on 1027  degrees of freedom
## Residual deviance: 139.17  on 1021  degrees of freedom
## AIC: 153.17
## 
## Number of Fisher Scoring iterations: 9</code></pre>
<pre class="r"><code>predict_sublegendary_fit&lt;-glm(status ~ attack + defense + sp_attack + sp_defense + hp + speed, family = binomial, data = predict_sublegendary)
summary(predict_sublegendary_fit)</code></pre>
<pre><code>## 
## Call:
## glm(formula = status ~ attack + defense + sp_attack + sp_defense + 
##     hp + speed, family = binomial, data = predict_sublegendary)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -2.7810  -0.2909  -0.1950  -0.1060   2.8255  
## 
## Coefficients:
##              Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept) -8.665698   0.926103  -9.357  &lt; 2e-16 ***
## attack       0.001367   0.005814   0.235  0.81410    
## defense      0.015796   0.006463   2.444  0.01452 *  
## sp_attack    0.014333   0.005369   2.669  0.00760 ** 
## sp_defense   0.010304   0.007030   1.466  0.14274    
## hp           0.006161   0.007010   0.879  0.37950    
## speed        0.018975   0.006196   3.063  0.00219 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 369.58  on 1027  degrees of freedom
## Residual deviance: 300.34  on 1021  degrees of freedom
## AIC: 314.34
## 
## Number of Fisher Scoring iterations: 7</code></pre>
<pre class="r"><code>predict_mythical_fit &lt;- glm(status ~ attack + defense + sp_attack + sp_defense + hp + speed, family = binomial, data = predict_mythical)
summary(predict_mythical_fit)</code></pre>
<pre><code>## 
## Call:
## glm(formula = status ~ attack + defense + sp_attack + sp_defense + 
##     hp + speed, family = binomial, data = predict_mythical)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -1.3806  -0.2221  -0.1319  -0.0748   3.4963  
## 
## Coefficients:
##              Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept) -9.315710   1.056971  -8.814  &lt; 2e-16 ***
## attack       0.005908   0.006756   0.875 0.381833    
## defense      0.015684   0.008368   1.874 0.060903 .  
## sp_attack    0.020430   0.006481   3.152 0.001620 ** 
## sp_defense   0.006592   0.009100   0.724 0.468797    
## hp          -0.009267   0.009377  -0.988 0.323045    
## speed        0.025713   0.007518   3.420 0.000626 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 264.12  on 1027  degrees of freedom
## Residual deviance: 204.01  on 1021  degrees of freedom
## AIC: 218.01
## 
## Number of Fisher Scoring iterations: 7</code></pre>
<p>The legendary model shows that all of the stats help predict legendary status. This finding makes sense because legendary Pokemon are usually good at all of their stats even the stats that aren’t their best. Furthermore, there are a large number of stat combinations that legendaries fulfill. Interestingly, the attack stat and defensive stats are less significant than the others. Because legendaries tend to be more offensive than defensive, this is not too surprising. They even have more of a tendency of specializing in special attack over physical attack.</p>
<p>According to the sub-legendary model, speed, special attack, and defense (in that order) are the defining stats of sub-legendaries. For mythical Pokemon, it is speed followed by special attack. It is worth noting that defense, in the mythical model, almost makes the statistically significant cut-off.</p>
<p>The next step is to create more representative models for plotting using what we learned from the first models.</p>
<pre class="r"><code>#Better Legendary model 
predict_legendary_fit1 &lt;- glm(status ~ total_points, family = binomial, data = predict_legendary)
summary(predict_legendary_fit1)</code></pre>
<pre><code>## 
## Call:
## glm(formula = status ~ total_points, family = binomial, data = predict_legendary)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -1.6633  -0.1094  -0.0465  -0.0081   5.2191  
## 
## Coefficients:
##                Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)  -19.278799   2.130088  -9.051   &lt;2e-16 ***
## total_points   0.028296   0.003359   8.424   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 331.70  on 1027  degrees of freedom
## Residual deviance: 146.55  on 1026  degrees of freedom
## AIC: 150.55
## 
## Number of Fisher Scoring iterations: 9</code></pre>
<pre class="r"><code>#Better Sub-Legndary Model
predict_sublegendary_fit1 &lt;-glm(status ~ speed + sp_attack + defense, family = binomial, data = predict_sublegendary)
summary(predict_sublegendary_fit1)</code></pre>
<pre><code>## 
## Call:
## glm(formula = status ~ speed + sp_attack + defense, family = binomial, 
##     data = predict_sublegendary)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -2.0997  -0.2986  -0.1938  -0.1162   2.9475  
## 
## Coefficients:
##              Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept) -8.083170   0.812345  -9.950  &lt; 2e-16 ***
## speed        0.019957   0.005837   3.419 0.000628 ***
## sp_attack    0.018272   0.004800   3.806 0.000141 ***
## defense      0.021169   0.004901   4.319 1.57e-05 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 369.58  on 1027  degrees of freedom
## Residual deviance: 303.69  on 1024  degrees of freedom
## AIC: 311.69
## 
## Number of Fisher Scoring iterations: 7</code></pre>
<pre class="r"><code>#Better Mythical Model
predict_mythical_fit1 &lt;- glm(status ~ sp_attack + speed + sp_attack*speed, family = binomial, data = predict_mythical)
summary(predict_mythical_fit1)</code></pre>
<pre><code>## 
## Call:
## glm(formula = status ~ sp_attack + speed + sp_attack * speed, 
##     family = binomial, data = predict_mythical)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -1.0016  -0.2432  -0.1273  -0.0743   3.5398  
## 
## Coefficients:
##                   Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)     -9.9278318  2.0807822  -4.771 1.83e-06 ***
## sp_attack        0.0451014  0.0188613   2.391   0.0168 *  
## speed            0.0464912  0.0201305   2.309   0.0209 *  
## sp_attack:speed -0.0002120  0.0001754  -1.209   0.2267    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 264.12  on 1027  degrees of freedom
## Residual deviance: 211.63  on 1024  degrees of freedom
## AIC: 219.63
## 
## Number of Fisher Scoring iterations: 8</code></pre>
<pre class="r"><code>#Even Better Mythical Model
predict_mythical_fit2 &lt;- glm(status ~ sp_attack + speed, family = binomial, data = predict_mythical)
summary(predict_mythical_fit2)</code></pre>
<pre><code>## 
## Call:
## glm(formula = status ~ sp_attack + speed, family = binomial, 
##     data = predict_mythical)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -1.2757  -0.2252  -0.1400  -0.0951   3.3491  
## 
## Coefficients:
##              Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept) -7.721022   0.776369  -9.945  &lt; 2e-16 ***
## sp_attack    0.023575   0.005787   4.073 4.63e-05 ***
## speed        0.024111   0.007276   3.314  0.00092 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 264.12  on 1027  degrees of freedom
## Residual deviance: 213.13  on 1025  degrees of freedom
## AIC: 219.13
## 
## Number of Fisher Scoring iterations: 7</code></pre>
<p>While attempting to improve the models for simplicity, something interesting happened to the sub-legendary and mythical models. In the sub-legendary model, defense became the most significant of the three variables followed by special attack and speed.</p>
<p>An interaction term (special attack and speed) was included in the mythical model because there was a possibility that the two stats together could help better predict mythical status. As it turns out, the interaction is statistically insignificant. Additionally, special attack becomes the better predictor when handling the two variables alone. For this reason, a third model was made for predicting mythical Pokemon.</p>
<pre class="r"><code>#Validation Analysis of Models 
prob_legendary&lt;- predict(predict_legendary_fit1, predict_legendary, type = &quot;response&quot;)
table(Predicted_Value = prob_legendary &gt; 0.5 , Actual_Value = predict_legendary$status )</code></pre>
<pre><code>##                Actual_Value
## Predicted_Value   0   1
##           FALSE 981  26
##           TRUE    8  13</code></pre>
<pre class="r"><code>prob_sublegendary&lt;- predict(predict_sublegendary_fit1, predict_sublegendary, type = &quot;response&quot;)
table(Predicted_Value = prob_sublegendary &gt; 0.5 , Actual_Value = predict_sublegendary$status )</code></pre>
<pre><code>##                Actual_Value
## Predicted_Value   0   1
##           FALSE 982  45
##           TRUE    1   0</code></pre>
<pre class="r"><code>prob_mythical&lt;- predict(predict_mythical_fit2, predict_mythical, type = &quot;response&quot;)
table(Predicted_Value = prob_mythical &gt; 0.5 , Actual_Value = predict_mythical$status )</code></pre>
<pre><code>##                Actual_Value
## Predicted_Value   0   1
##           FALSE 997  28
##           TRUE    2   1</code></pre>
<p>The legendary model’s accuracy was 96.7 percent. The sub-legendary model’s accuracy is 95.5 percent, and the mythical model’s accuracy was equal to 97.2 percent. However, we, once again, are finding that the recall of the models are not great. The recall for the legendary, sub-legendary, and mythical models are 33%, 0%, and 3.5 percent, respectively. Like before, these models seem to be too conservative because they are better at classifying the non-specified categories of Pokemon rather than the one specified category we are looking for. This means that the 0.5 threshold values need to be decreased to allow for better classification to occur. But once again, this is beyond this task’s goal.</p>
<p>Here are some plots so we can visualize all of this:</p>
<pre class="r"><code>#Legendary Logistic Regression
visreg(predict_legendary_fit1, &quot;total_points&quot;,
       rug = FALSE ,
       band= FALSE,
       xlab = &quot;Total Points&quot;, 
       ylab = &quot;Probabiltiy of Being a Legendary&quot;,
       line= list(col =&quot;darkviolet&quot;),
       fill = list(fill = &quot;grey80&quot;),
       scale=&quot;response&quot;,
       gg = TRUE)+ 
       theme_bw()+ 
       labs(title = &quot;Logistic Regression Prediction of Legendary Status&quot;)+
       theme(legend.position = &quot;none&quot;,
              text = element_text(family = &quot;Georgia&quot;), 
             plot.title = element_text(size = 15, margin(b = 10), hjust = 0.5, family = &quot;Georgia&quot;))</code></pre>
<p><img src="06--Chapter-5_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<pre class="r"><code>#Sub-Legendary Logistic Regression
library(visreg)
visreg(predict_sublegendary_fit1, &quot;defense&quot;, by = &quot;sp_attack&quot;,
       rug = FALSE ,
       band= FALSE,
       xlab = &quot;Defense&quot;, 
       ylab = &quot;Probabiltiy of Being a Sub-Legendary&quot;,
       line= list(col =&quot;green&quot;),
       fill = list(fill = &quot;grey80&quot;),
       scale=&quot;response&quot;,
       gg = TRUE)+ 
       theme_bw()+ 
       labs(title = &quot;Logistic Regression Prediction of Sub-Legendary Status&quot;)+
       theme(legend.position = &quot;none&quot;,
              text = element_text(family = &quot;Georgia&quot;), 
             plot.title = element_text(size = 15, margin(b = 10), hjust = 0.5, family = &quot;Georgia&quot;))</code></pre>
<p><img src="06--Chapter-5_files/figure-html/unnamed-chunk-5-2.png" width="672" /></p>
<pre class="r"><code>visreg(predict_sublegendary_fit1, &quot;defense&quot;, by = &quot;speed&quot;,
       rug = FALSE ,
       band= FALSE,
       xlab = &quot;Defense&quot;, 
       ylab = &quot;Probabiltiy of Being a Sub-Legendary&quot;,
       line= list(col =&quot;green&quot;),
       fill = list(fill = &quot;grey80&quot;),
       scale=&quot;response&quot;,
       gg = TRUE)+ 
       theme_bw()+ 
       labs(title = &quot;Logistic Regression Prediction of Sub-Legendary Status&quot;)+
       theme(legend.position = &quot;none&quot;,
              text = element_text(family = &quot;Georgia&quot;), 
             plot.title = element_text(size = 15, margin(b = 10), hjust = 0.5, family = &quot;Georgia&quot;))</code></pre>
<p><img src="06--Chapter-5_files/figure-html/unnamed-chunk-5-3.png" width="672" /></p>
<pre class="r"><code>visreg(predict_sublegendary_fit1, &quot;sp_attack&quot;, by = &quot;speed&quot;,
       rug = FALSE ,
       band= FALSE,
       xlab = &quot;Special Attack&quot;, 
       ylab = &quot;Probabiltiy of Being a Sub-Legendary&quot;,
       line= list(col =&quot;green&quot;),
       fill = list(fill = &quot;grey80&quot;),
       scale=&quot;response&quot;,
       gg = TRUE)+ 
       theme_bw()+ 
       labs(title = &quot;Logistic Regression Prediction of Sub-Legendary Status&quot;)+
       theme(legend.position = &quot;none&quot;,
              text = element_text(family = &quot;Georgia&quot;), 
             plot.title = element_text(size = 15, margin(b = 10), hjust = 0.5, family = &quot;Georgia&quot;))</code></pre>
<p><img src="06--Chapter-5_files/figure-html/unnamed-chunk-5-4.png" width="672" /></p>
<pre class="r"><code>#Mythical Logistirc Regression
visreg(predict_mythical_fit2, &quot;sp_attack&quot;, by = &quot;speed&quot;,
       rug = FALSE ,
       band= FALSE,
       xlab = &quot;Special Attack&quot;, 
       ylab = &quot;Probabiltiy of Being a Mythical Pokemon&quot;,
       line= list(col =&quot;deeppink&quot;),
       fill = list(fill = &quot;grey80&quot;),
       scale=&quot;response&quot;,
       gg = TRUE)+ 
       theme_bw()+ 
       labs(title = &quot;Logistic Regression Prediction of Mythical Status&quot;)+
       theme(legend.position = &quot;none&quot;,
              text = element_text(family = &quot;Georgia&quot;), 
             plot.title = element_text(size = 15, margin(b = 10), hjust = 0.5, family = &quot;Georgia&quot;))</code></pre>
<p><img src="06--Chapter-5_files/figure-html/unnamed-chunk-5-5.png" width="672" /></p>
<p>In the legendary regression, we see a pretty straight forward graph where the probability of being a legendary Pokemon before about 500 total points is basically 0. After 750 total points, the probability is more than 87.5 percent. The three sub-legendary logistic regressions show how having different amounts of particular stats affect the model’s ability to predict sub-legendary status. The essential things to note are that when a Pokemon has high defense, having high special attack or high speed helps better predict sub-legendary status. Although not as strong as the first two graphs, the last plot shows how the presence of both high special attack and high speed helps predict sub-legendary status to lesser degree. Finally, for mythical status, if a Pokemon had both high special attack and high speed, the probability of being a mythical Pokemon increases.</p>
</div>
<div id="task-15-do-pokemon-with-better-designs-have-higher-stats" class="section level2">
<h2>Task 15: Do pokemon with better designs have higher stats?</h2>
<p>This task is actually pretty simple because we are only trying to figure out the relationship between one explanatory variable (design) and one response variable (total points).</p>
<p>The hardest part for this task is going to be creating the data frame we need. We need gather the 8 separate surveys that were used to get design scores, create a useful data frame with them, and combine them with the data we have been using.</p>
<pre class="r"><code>#Read in data frames
library(readr)

# Survey 1
pokemon_generation1 &lt;- read_csv(&quot;C:/Users/laryl/Desktop/Data Sets/Pokemon_Survey_Generation_1.csv&quot;)

#Survey 2
pokemon_generation2 &lt;- read_csv(&quot;C:/Users/laryl/Desktop/Data Sets/Pokemon_Survey_Generation_2.csv&quot;)

# Survey 3
pokemon_generation3  &lt;- read_csv(&quot;C:/Users/laryl/Desktop/Data Sets/Pokemon_Survey_Generation_3.csv&quot;)

#Survey 4
pokemon_generation4 &lt;- read_csv(&quot;C:/Users/laryl/Desktop/Data Sets/Pokemon_Survey_Generation_4 .csv&quot;)

# Survey 5
pokemon_generation5 &lt;- read_csv(&quot;C:/Users/laryl/Desktop/Data Sets/Pokemon_Survey_Generation_5.csv&quot;)

# Survey 6
pokemon_generation6  &lt;- read_csv(&quot;C:/Users/laryl/Desktop/Data Sets/Pokemon_Survey_Generation_6 .csv&quot;)

# Survey 7
pokemon_generation7 &lt;- read_csv(&quot;C:/Users/laryl/Desktop/Data Sets/Pokemon_Survey_Generation_7.csv&quot;)

# Survey 8
pokemon_generation8  &lt;- read_csv(&quot;C:/Users/laryl/Desktop/Data Sets/Pokemon_Survey_Generation_8.csv&quot;)</code></pre>
<p>At the moment, each Pokemon in these data frames have a design score that was given to them by respondents to the surveys. Those scores are listed in variables called “obs”. For example, the generation 1 survey (pokemon_generation1) has 12 variables in total. The first variable (ï..num) represents the Pokemon’s pokedex number (a unique number assigned to each Pokemon). The last 11 variables (obs_1- obs 11) are the 11 respondents to the survey. So each of the 11 respondents rated each Pokemon in the survey from 1-10.</p>
<p>Now we need to take the mean of each Pokemon’s score and tern it into its own variable for all 8 surveys.</p>
<pre class="r"><code>#Take the mean of all of the observations and call that new variable design_mean

library(dplyr)
pokemon_generation1_des &lt;- pokemon_generation1 %&gt;%
  mutate(design_mean = rowMeans(select(pokemon_generation1, starts_with(&quot;obs&quot;))))

pokemon_generation2_des &lt;- pokemon_generation2 %&gt;%
  mutate(design_mean = rowMeans(select(pokemon_generation2, starts_with(&quot;obs&quot;))))

pokemon_generation3_des&lt;- pokemon_generation3 %&gt;%
  mutate(design_mean =  rowMeans(select(pokemon_generation3, starts_with(&quot;obs&quot;))))

pokemon_generation4_des &lt;- pokemon_generation4 %&gt;%
  mutate(design_mean = rowMeans(select(pokemon_generation4, starts_with(&quot;obs&quot;))))


pokemon_generation5_des &lt;- pokemon_generation5 %&gt;%
  mutate(design_mean = rowMeans(select(pokemon_generation5, starts_with(&quot;obs&quot;))))

pokemon_generation6_des &lt;- pokemon_generation6 %&gt;%
  mutate(design_mean = rowMeans(select(pokemon_generation6, starts_with(&quot;obs&quot;))))

pokemon_generation7_des &lt;- pokemon_generation7 %&gt;%
  mutate(design_mean = rowMeans(select(pokemon_generation7, starts_with(&quot;obs&quot;))))

pokemon_generation8_des &lt;- pokemon_generation8 %&gt;%
  mutate(design_mean = rowMeans(select(pokemon_generation8, starts_with(&quot;obs&quot;))))</code></pre>
<p>Let’s now filter out all of the useless variables</p>
<pre class="r"><code>#Create new dataframe with just the pokedex number and design mean
pokemon_generation1_des&lt;-pokemon_generation1_des %&gt;%
  select(num, design_mean)
pokemon_generation2_des&lt;- pokemon_generation2_des %&gt;%
  select(num, design_mean)
pokemon_generation3_des&lt;- pokemon_generation3_des %&gt;%
  select(num, design_mean)
pokemon_generation4_des&lt;- pokemon_generation4_des %&gt;%
  select(num, design_mean)
pokemon_generation5_des&lt;- pokemon_generation5_des %&gt;%
  select(num, design_mean)
pokemon_generation6_des&lt;- pokemon_generation6_des %&gt;%
  select(num, design_mean)
pokemon_generation7_des&lt;- pokemon_generation7_des %&gt;%
  select(num, design_mean)
pokemon_generation8_des&lt;- pokemon_generation8_des %&gt;%
  select(num, design_mean)</code></pre>
<p>We need to now bind all of these survey data frames into a single survey data frame.</p>
<pre class="r"><code>pokemon_design&lt;- rbind(pokemon_generation1_des, pokemon_generation2_des, pokemon_generation3_des, pokemon_generation4_des, pokemon_generation5_des, pokemon_generation6_des, pokemon_generation7_des, pokemon_generation8_des)

pokemon_design</code></pre>
<pre><code>## # A tibble: 1,015 x 2
##    num   design_mean
##    &lt;chr&gt;       &lt;dbl&gt;
##  1 1            8.09
##  2 2            7.55
##  3 3            5.45
##  4 3M           6.55
##  5 4            6.36
##  6 5            6.45
##  7 6            8.36
##  8 6MX          7.09
##  9 6MY          8.91
## 10 7            7.91
## # ... with 1,005 more rows</code></pre>
<p>Now, in order to combine the design data frame with the data we have been using throughout this project, we need to make sure it has the same amount of observations. The design data frame has 1015 Pokemon whereas the project data frame has 1028 Pokemon. Unfortunately, this means playing detective to find all of the observations that do not match each other from both data frames.</p>
<pre class="r"><code>#See the number of Pokemon per generation
table(pokemon_data_clean$generation)</code></pre>
<pre><code>## 
##   1   2   3   4   5   6   7   8 
## 192 107 165 121 171  85  99  88</code></pre>
<pre class="r"><code>#Create new project dataframe with necessary variables 
pokemon_data_pure &lt;- pokemon_data_full[, c(2,3,18)]

#Eliminating mismatched obervations 
pokemon_data_pure&lt;-pokemon_data_pure[c(-414,-415,-416, -560, -786,-787,-790,-791,-821, -822, -823, -825, -826,-827,-868),]

pokemon_design&lt;- pokemon_design[c(-782, -785),]

#Combine dataframes
pokemon_design_vs_points &lt;-cbind(pokemon_data_pure, pokemon_design)

#Removing Outlier
pokemon_design_vs_points &lt;-pokemon_design_vs_points[-1013,]

pokemon_design_vs_points</code></pre>
<pre><code>##      pokedex_number                              name total_points
## 1                 1                         Bulbasaur          318
## 2                 2                           Ivysaur          405
## 3                 3                          Venusaur          525
## 4                 3                     Mega Venusaur          625
## 5                 4                        Charmander          309
## 6                 5                        Charmeleon          405
## 7                 6                         Charizard          534
## 8                 6                  Mega Charizard X          634
## 9                 6                  Mega Charizard Y          634
## 10                7                          Squirtle          314
## 11                8                         Wartortle          405
## 12                9                         Blastoise          530
## 13                9                    Mega Blastoise          630
## 14               10                          Caterpie          195
## 15               11                           Metapod          205
## 16               12                        Butterfree          395
## 17               13                            Weedle          195
## 18               14                            Kakuna          205
## 19               15                          Beedrill          395
## 20               15                     Mega Beedrill          495
## 21               16                            Pidgey          251
## 22               17                         Pidgeotto          349
## 23               18                           Pidgeot          479
## 24               18                      Mega Pidgeot          579
## 25               19                           Rattata          253
## 26               19                    Alolan Rattata          253
## 27               20                          Raticate          413
## 28               20                   Alolan Raticate          413
## 29               21                           Spearow          262
## 30               22                            Fearow          442
## 31               23                             Ekans          288
## 32               24                             Arbok          448
## 33               25                           Pikachu          320
## 34               25                   Partner Pikachu          430
## 35               26                            Raichu          485
## 36               26                     Alolan Raichu          485
## 37               27                         Sandshrew          300
## 38               27                  Alolan Sandshrew          300
## 39               28                         Sandslash          450
## 40               28                  Alolan Sandslash          450
## 41               29                        Nidoranâ\231\200          275
## 42               30                          Nidorina          365
## 43               31                         Nidoqueen          505
## 44               32                        Nidoranâ\231‚          273
## 45               33                          Nidorino          365
## 46               34                          Nidoking          505
## 47               35                          Clefairy          323
## 48               36                          Clefable          483
## 49               37                            Vulpix          299
## 50               37                     Alolan Vulpix          299
## 51               38                         Ninetales          505
## 52               38                  Alolan Ninetales          505
## 53               39                        Jigglypuff          270
## 54               40                        Wigglytuff          435
## 55               41                             Zubat          245
## 56               42                            Golbat          455
## 57               43                            Oddish          320
## 58               44                             Gloom          395
## 59               45                         Vileplume          490
## 60               46                             Paras          285
## 61               47                          Parasect          405
## 62               48                           Venonat          305
## 63               49                          Venomoth          450
## 64               50                           Diglett          265
## 65               50                    Alolan Diglett          265
## 66               51                           Dugtrio          425
## 67               51                    Alolan Dugtrio          425
## 68               52                            Meowth          290
## 69               52                     Alolan Meowth          290
## 70               52                   Galarian Meowth          290
## 71               53                           Persian          440
## 72               53                    Alolan Persian          440
## 73               54                           Psyduck          320
## 74               55                           Golduck          500
## 75               56                            Mankey          305
## 76               57                          Primeape          455
## 77               58                         Growlithe          350
## 78               59                          Arcanine          555
## 79               60                           Poliwag          300
## 80               61                         Poliwhirl          385
## 81               62                         Poliwrath          510
## 82               63                              Abra          310
## 83               64                           Kadabra          400
## 84               65                          Alakazam          500
## 85               65                     Mega Alakazam          600
## 86               66                            Machop          305
## 87               67                           Machoke          405
## 88               68                           Machamp          505
## 89               69                        Bellsprout          300
## 90               70                        Weepinbell          390
## 91               71                        Victreebel          490
## 92               72                         Tentacool          335
## 93               73                        Tentacruel          515
## 94               74                           Geodude          300
## 95               74                    Alolan Geodude          300
## 96               75                          Graveler          390
## 97               75                   Alolan Graveler          390
## 98               76                             Golem          495
## 99               76                      Alolan Golem          495
## 100              77                            Ponyta          410
## 101              77                   Galarian Ponyta          410
## 102              78                          Rapidash          500
## 103              78                 Galarian Rapidash          500
## 104              79                          Slowpoke          315
## 105              80                           Slowbro          490
## 106              80                      Mega Slowbro          590
## 107              81                         Magnemite          325
## 108              82                          Magneton          465
## 109              83                        Farfetch&#39;d          377
## 110              83               Galarian Farfetch&#39;d          377
## 111              84                             Doduo          310
## 112              85                            Dodrio          470
## 113              86                              Seel          325
## 114              87                           Dewgong          475
## 115              88                            Grimer          325
## 116              88                     Alolan Grimer          325
## 117              89                               Muk          500
## 118              89                        Alolan Muk          500
## 119              90                          Shellder          305
## 120              91                          Cloyster          525
## 121              92                            Gastly          310
## 122              93                           Haunter          405
## 123              94                            Gengar          500
## 124              94                       Mega Gengar          600
## 125              95                              Onix          385
## 126              96                           Drowzee          328
## 127              97                             Hypno          483
## 128              98                            Krabby          325
## 129              99                           Kingler          475
## 130             100                           Voltorb          330
## 131             101                         Electrode          490
## 132             102                         Exeggcute          325
## 133             103                         Exeggutor          530
## 134             103                  Alolan Exeggutor          530
## 135             104                            Cubone          320
## 136             105                           Marowak          425
## 137             105                    Alolan Marowak          425
## 138             106                         Hitmonlee          455
## 139             107                        Hitmonchan          455
## 140             108                         Lickitung          385
## 141             109                           Koffing          340
## 142             110                           Weezing          490
## 143             110                  Galarian Weezing          490
## 144             111                           Rhyhorn          345
## 145             112                            Rhydon          485
## 146             113                           Chansey          450
## 147             114                           Tangela          435
## 148             115                        Kangaskhan          490
## 149             115                   Mega Kangaskhan          590
## 150             116                            Horsea          295
## 151             117                            Seadra          440
## 152             118                           Goldeen          320
## 153             119                           Seaking          450
## 154             120                            Staryu          340
## 155             121                           Starmie          520
## 156             122                          Mr. Mime          460
## 157             122                 Galarian Mr. Mime          460
## 158             123                           Scyther          500
## 159             124                              Jynx          455
## 160             125                        Electabuzz          490
## 161             126                            Magmar          495
## 162             127                            Pinsir          500
## 163             127                       Mega Pinsir          600
## 164             128                            Tauros          490
## 165             129                          Magikarp          200
## 166             130                          Gyarados          540
## 167             130                     Mega Gyarados          640
## 168             131                            Lapras          535
## 169             132                             Ditto          288
## 170             133                             Eevee          325
## 171             133                     Partner Eevee          435
## 172             134                          Vaporeon          525
## 173             135                           Jolteon          525
## 174             136                           Flareon          525
## 175             137                           Porygon          395
## 176             138                           Omanyte          355
## 177             139                           Omastar          495
## 178             140                            Kabuto          355
## 179             141                          Kabutops          495
## 180             142                        Aerodactyl          515
## 181             142                   Mega Aerodactyl          615
## 182             143                           Snorlax          540
## 183             144                          Articuno          580
## 184             145                            Zapdos          580
## 185             146                           Moltres          580
## 186             147                           Dratini          300
## 187             148                         Dragonair          420
## 188             149                         Dragonite          600
## 189             150                            Mewtwo          680
## 190             150                     Mega Mewtwo X          780
## 191             150                     Mega Mewtwo Y          780
## 192             151                               Mew          600
## 193             152                         Chikorita          318
## 194             153                           Bayleef          405
## 195             154                          Meganium          525
## 196             155                         Cyndaquil          309
## 197             156                           Quilava          405
## 198             157                        Typhlosion          534
## 199             158                          Totodile          314
## 200             159                          Croconaw          405
## 201             160                        Feraligatr          530
## 202             161                           Sentret          215
## 203             162                            Furret          415
## 204             163                          Hoothoot          262
## 205             164                           Noctowl          452
## 206             165                            Ledyba          265
## 207             166                            Ledian          390
## 208             167                          Spinarak          250
## 209             168                           Ariados          400
## 210             169                            Crobat          535
## 211             170                          Chinchou          330
## 212             171                           Lanturn          460
## 213             172                             Pichu          205
## 214             173                            Cleffa          218
## 215             174                         Igglybuff          210
## 216             175                            Togepi          245
## 217             176                           Togetic          405
## 218             177                              Natu          320
## 219             178                              Xatu          470
## 220             179                            Mareep          280
## 221             180                           Flaaffy          365
## 222             181                          Ampharos          510
## 223             181                     Mega Ampharos          610
## 224             182                         Bellossom          490
## 225             183                            Marill          250
## 226             184                         Azumarill          420
## 227             185                         Sudowoodo          410
## 228             186                          Politoed          500
## 229             187                            Hoppip          250
## 230             188                          Skiploom          340
## 231             189                          Jumpluff          460
## 232             190                             Aipom          360
## 233             191                           Sunkern          180
## 234             192                          Sunflora          425
## 235             193                             Yanma          390
## 236             194                            Wooper          210
## 237             195                          Quagsire          430
## 238             196                            Espeon          525
## 239             197                           Umbreon          525
## 240             198                           Murkrow          405
## 241             199                          Slowking          490
## 242             200                        Misdreavus          435
## 243             201                             Unown          336
## 244             202                         Wobbuffet          405
## 245             203                         Girafarig          455
## 246             204                            Pineco          290
## 247             205                        Forretress          465
## 248             206                         Dunsparce          415
## 249             207                            Gligar          430
## 250             208                           Steelix          510
## 251             208                      Mega Steelix          610
## 252             209                          Snubbull          300
## 253             210                          Granbull          450
## 254             211                          Qwilfish          440
## 255             212                            Scizor          500
## 256             212                       Mega Scizor          600
## 257             213                           Shuckle          505
## 258             214                         Heracross          500
## 259             214                    Mega Heracross          600
## 260             215                           Sneasel          430
## 261             216                         Teddiursa          330
## 262             217                          Ursaring          500
## 263             218                            Slugma          250
## 264             219                          Magcargo          430
## 265             220                            Swinub          250
## 266             221                         Piloswine          450
## 267             222                           Corsola          410
## 268             222                  Galarian Corsola          410
## 269             223                          Remoraid          300
## 270             224                         Octillery          480
## 271             225                          Delibird          330
## 272             226                           Mantine          485
## 273             227                          Skarmory          465
## 274             228                          Houndour          330
## 275             229                          Houndoom          500
## 276             229                     Mega Houndoom          600
## 277             230                           Kingdra          540
## 278             231                            Phanpy          330
## 279             232                           Donphan          500
## 280             233                          Porygon2          515
## 281             234                          Stantler          465
## 282             235                          Smeargle          250
## 283             236                           Tyrogue          210
## 284             237                         Hitmontop          455
## 285             238                          Smoochum          305
## 286             239                            Elekid          360
## 287             240                             Magby          365
## 288             241                           Miltank          490
## 289             242                           Blissey          540
## 290             243                            Raikou          580
## 291             244                             Entei          580
## 292             245                           Suicune          580
## 293             246                          Larvitar          300
## 294             247                           Pupitar          410
## 295             248                         Tyranitar          600
## 296             248                    Mega Tyranitar          700
## 297             249                             Lugia          680
## 298             250                             Ho-oh          680
## 299             251                            Celebi          600
## 300             252                           Treecko          310
## 301             253                           Grovyle          405
## 302             254                          Sceptile          530
## 303             254                     Mega Sceptile          630
## 304             255                           Torchic          310
## 305             256                         Combusken          405
## 306             257                          Blaziken          530
## 307             257                     Mega Blaziken          630
## 308             258                            Mudkip          310
## 309             259                         Marshtomp          405
## 310             260                          Swampert          535
## 311             260                     Mega Swampert          635
## 312             261                         Poochyena          220
## 313             262                         Mightyena          420
## 314             263                         Zigzagoon          240
## 315             263                Galarian Zigzagoon          240
## 316             264                           Linoone          420
## 317             264                  Galarian Linoone          420
## 318             265                           Wurmple          195
## 319             266                           Silcoon          205
## 320             267                         Beautifly          395
## 321             268                           Cascoon          205
## 322             269                            Dustox          385
## 323             270                             Lotad          220
## 324             271                            Lombre          340
## 325             272                          Ludicolo          480
## 326             273                            Seedot          220
## 327             274                           Nuzleaf          340
## 328             275                           Shiftry          480
## 329             276                           Taillow          270
## 330             277                           Swellow          455
## 331             278                           Wingull          270
## 332             279                          Pelipper          440
## 333             280                             Ralts          198
## 334             281                            Kirlia          278
## 335             282                         Gardevoir          518
## 336             282                    Mega Gardevoir          618
## 337             283                           Surskit          269
## 338             284                        Masquerain          454
## 339             285                         Shroomish          295
## 340             286                           Breloom          460
## 341             287                           Slakoth          280
## 342             288                          Vigoroth          440
## 343             289                           Slaking          670
## 344             290                           Nincada          266
## 345             291                           Ninjask          456
## 346             292                          Shedinja          236
## 347             293                           Whismur          240
## 348             294                           Loudred          360
## 349             295                           Exploud          490
## 350             296                          Makuhita          237
## 351             297                          Hariyama          474
## 352             298                           Azurill          190
## 353             299                          Nosepass          375
## 354             300                            Skitty          260
## 355             301                          Delcatty          400
## 356             302                           Sableye          380
## 357             302                      Mega Sableye          480
## 358             303                            Mawile          380
## 359             303                       Mega Mawile          480
## 360             304                              Aron          330
## 361             305                            Lairon          430
## 362             306                            Aggron          530
## 363             306                       Mega Aggron          630
## 364             307                          Meditite          280
## 365             308                          Medicham          410
## 366             308                     Mega Medicham          510
## 367             309                         Electrike          295
## 368             310                         Manectric          475
## 369             310                    Mega Manectric          575
## 370             311                            Plusle          405
## 371             312                             Minun          405
## 372             313                           Volbeat          430
## 373             314                          Illumise          430
## 374             315                           Roselia          400
## 375             316                            Gulpin          302
## 376             317                            Swalot          467
## 377             318                          Carvanha          305
## 378             319                          Sharpedo          460
## 379             319                     Mega Sharpedo          560
## 380             320                           Wailmer          400
## 381             321                           Wailord          500
## 382             322                             Numel          305
## 383             323                          Camerupt          460
## 384             323                     Mega Camerupt          560
## 385             324                           Torkoal          470
## 386             325                            Spoink          330
## 387             326                           Grumpig          470
## 388             327                            Spinda          360
## 389             328                          Trapinch          290
## 390             329                           Vibrava          340
## 391             330                            Flygon          520
## 392             331                            Cacnea          335
## 393             332                          Cacturne          475
## 394             333                            Swablu          310
## 395             334                           Altaria          490
## 396             334                      Mega Altaria          590
## 397             335                          Zangoose          458
## 398             336                           Seviper          458
## 399             337                          Lunatone          460
## 400             338                           Solrock          460
## 401             339                          Barboach          288
## 402             340                          Whiscash          468
## 403             341                          Corphish          308
## 404             342                         Crawdaunt          468
## 405             343                            Baltoy          300
## 406             344                           Claydol          500
## 407             345                            Lileep          355
## 408             346                           Cradily          495
## 409             347                           Anorith          355
## 410             348                           Armaldo          495
## 411             349                            Feebas          200
## 412             350                           Milotic          540
## 413             351                          Castform          420
## 417             352                           Kecleon          440
## 418             353                           Shuppet          295
## 419             354                           Banette          455
## 420             354                      Mega Banette          555
## 421             355                           Duskull          295
## 422             356                          Dusclops          455
## 423             357                           Tropius          460
## 424             358                          Chimecho          455
## 425             359                             Absol          465
## 426             359                        Mega Absol          565
## 427             360                            Wynaut          260
## 428             361                           Snorunt          300
## 429             362                            Glalie          480
## 430             362                       Mega Glalie          580
## 431             363                            Spheal          290
## 432             364                            Sealeo          410
## 433             365                           Walrein          530
## 434             366                          Clamperl          345
## 435             367                           Huntail          485
## 436             368                          Gorebyss          485
## 437             369                         Relicanth          485
## 438             370                           Luvdisc          330
## 439             371                             Bagon          300
## 440             372                           Shelgon          420
## 441             373                         Salamence          600
## 442             373                    Mega Salamence          700
## 443             374                            Beldum          300
## 444             375                            Metang          420
## 445             376                         Metagross          600
## 446             376                    Mega Metagross          700
## 447             377                          Regirock          580
## 448             378                            Regice          580
## 449             379                         Registeel          580
## 450             380                            Latias          600
## 451             380                       Mega Latias          700
## 452             381                            Latios          600
## 453             381                       Mega Latios          700
## 454             382                            Kyogre          670
## 455             382                     Primal Kyogre          770
## 456             383                           Groudon          670
## 457             383                    Primal Groudon          770
## 458             384                          Rayquaza          680
## 459             384                     Mega Rayquaza          780
## 460             385                           Jirachi          600
## 461             386               Deoxys Normal Forme          600
## 462             386               Deoxys Attack Forme          600
## 463             386              Deoxys Defense Forme          600
## 464             386                Deoxys Speed Forme          600
## 465             387                           Turtwig          318
## 466             388                            Grotle          405
## 467             389                          Torterra          525
## 468             390                          Chimchar          309
## 469             391                          Monferno          405
## 470             392                         Infernape          534
## 471             393                            Piplup          314
## 472             394                          Prinplup          405
## 473             395                          Empoleon          530
## 474             396                            Starly          245
## 475             397                          Staravia          340
## 476             398                         Staraptor          485
## 477             399                            Bidoof          250
## 478             400                           Bibarel          410
## 479             401                         Kricketot          194
## 480             402                        Kricketune          384
## 481             403                             Shinx          263
## 482             404                             Luxio          363
## 483             405                            Luxray          523
## 484             406                             Budew          280
## 485             407                          Roserade          515
## 486             408                          Cranidos          350
## 487             409                         Rampardos          495
## 488             410                          Shieldon          350
## 489             411                         Bastiodon          495
## 490             412                             Burmy          224
## 491             413              Wormadam Plant Cloak          424
## 492             413              Wormadam Sandy Cloak          424
## 493             413              Wormadam Trash Cloak          424
## 494             414                            Mothim          424
## 495             415                            Combee          244
## 496             416                         Vespiquen          474
## 497             417                         Pachirisu          405
## 498             418                            Buizel          330
## 499             419                          Floatzel          495
## 500             420                           Cherubi          275
## 501             421                           Cherrim          450
## 502             422                           Shellos          325
## 503             423                         Gastrodon          475
## 504             424                           Ambipom          482
## 505             425                          Drifloon          348
## 506             426                          Drifblim          498
## 507             427                           Buneary          350
## 508             428                           Lopunny          480
## 509             428                      Mega Lopunny          580
## 510             429                         Mismagius          495
## 511             430                         Honchkrow          505
## 512             431                           Glameow          310
## 513             432                           Purugly          452
## 514             433                         Chingling          285
## 515             434                            Stunky          329
## 516             435                          Skuntank          479
## 517             436                           Bronzor          300
## 518             437                          Bronzong          500
## 519             438                            Bonsly          290
## 520             439                          Mime Jr.          310
## 521             440                           Happiny          220
## 522             441                            Chatot          411
## 523             442                         Spiritomb          485
## 524             443                             Gible          300
## 525             444                            Gabite          410
## 526             445                          Garchomp          600
## 527             445                     Mega Garchomp          700
## 528             446                          Munchlax          390
## 529             447                             Riolu          285
## 530             448                           Lucario          525
## 531             448                      Mega Lucario          625
## 532             449                        Hippopotas          330
## 533             450                         Hippowdon          525
## 534             451                           Skorupi          330
## 535             452                           Drapion          500
## 536             453                          Croagunk          300
## 537             454                         Toxicroak          490
## 538             455                         Carnivine          454
## 539             456                           Finneon          330
## 540             457                          Lumineon          460
## 541             458                           Mantyke          345
## 542             459                            Snover          334
## 543             460                         Abomasnow          494
## 544             460                    Mega Abomasnow          594
## 545             461                           Weavile          510
## 546             462                         Magnezone          535
## 547             463                        Lickilicky          515
## 548             464                         Rhyperior          535
## 549             465                         Tangrowth          535
## 550             466                        Electivire          540
## 551             467                         Magmortar          540
## 552             468                          Togekiss          545
## 553             469                           Yanmega          515
## 554             470                           Leafeon          525
## 555             471                           Glaceon          525
## 556             472                           Gliscor          510
## 557             473                         Mamoswine          530
## 558             474                         Porygon-Z          535
## 559             475                           Gallade          518
## 561             476                         Probopass          525
## 562             477                          Dusknoir          525
## 563             478                          Froslass          480
## 564             479                             Rotom          440
## 565             479                        Heat Rotom          520
## 566             479                        Wash Rotom          520
## 567             479                       Frost Rotom          520
## 568             479                         Fan Rotom          520
## 569             479                         Mow Rotom          520
## 570             480                              Uxie          580
## 571             481                           Mesprit          580
## 572             482                             Azelf          580
## 573             483                            Dialga          680
## 574             484                            Palkia          680
## 575             485                           Heatran          600
## 576             486                         Regigigas          670
## 577             487            Giratina Altered Forme          680
## 578             487             Giratina Origin Forme          680
## 579             488                         Cresselia          600
## 580             489                            Phione          480
## 581             490                           Manaphy          600
## 582             491                           Darkrai          600
## 583             492                Shaymin Land Forme          600
## 584             492                 Shaymin Sky Forme          600
## 585             493                            Arceus          720
## 586             494                           Victini          600
## 587             495                             Snivy          308
## 588             496                           Servine          413
## 589             497                         Serperior          528
## 590             498                             Tepig          308
## 591             499                           Pignite          418
## 592             500                            Emboar          528
## 593             501                          Oshawott          308
## 594             502                            Dewott          413
## 595             503                          Samurott          528
## 596             504                            Patrat          255
## 597             505                           Watchog          420
## 598             506                          Lillipup          275
## 599             507                           Herdier          370
## 600             508                         Stoutland          500
## 601             509                          Purrloin          281
## 602             510                           Liepard          446
## 603             511                           Pansage          316
## 604             512                          Simisage          498
## 605             513                           Pansear          316
## 606             514                          Simisear          498
## 607             515                           Panpour          316
## 608             516                          Simipour          498
## 609             517                             Munna          292
## 610             518                          Musharna          487
## 611             519                            Pidove          264
## 612             520                         Tranquill          358
## 613             521                          Unfezant          488
## 614             522                           Blitzle          295
## 615             523                         Zebstrika          497
## 616             524                        Roggenrola          280
## 617             525                           Boldore          390
## 618             526                          Gigalith          515
## 619             527                            Woobat          323
## 620             528                           Swoobat          425
## 621             529                           Drilbur          328
## 622             530                         Excadrill          508
## 623             531                            Audino          445
## 624             531                       Mega Audino          545
## 625             532                           Timburr          305
## 626             533                           Gurdurr          405
## 627             534                        Conkeldurr          505
## 628             535                           Tympole          294
## 629             536                         Palpitoad          384
## 630             537                        Seismitoad          509
## 631             538                             Throh          465
## 632             539                              Sawk          465
## 633             540                          Sewaddle          310
## 634             541                          Swadloon          380
## 635             542                          Leavanny          500
## 636             543                          Venipede          260
## 637             544                        Whirlipede          360
## 638             545                         Scolipede          485
## 639             546                          Cottonee          280
## 640             547                        Whimsicott          480
## 641             548                           Petilil          280
## 642             549                         Lilligant          480
## 643             550         Basculin Red-Striped Form          460
## 644             550        Basculin Blue-Striped Form          460
## 645             551                           Sandile          292
## 646             552                          Krokorok          351
## 647             553                        Krookodile          519
## 648             554                          Darumaka          315
## 649             554                 Galarian Darumaka          315
## 650             555          Darmanitan Standard Mode          480
## 651             555               Darmanitan Zen Mode          540
## 652             555 Darmanitan Galarian Standard Mode          480
## 653             555      Darmanitan Galarian Zen Mode          540
## 654             556                          Maractus          461
## 655             557                           Dwebble          325
## 656             558                           Crustle          485
## 657             559                           Scraggy          348
## 658             560                           Scrafty          488
## 659             561                          Sigilyph          490
## 660             562                            Yamask          303
## 661             562                   Galarian Yamask          303
## 662             563                        Cofagrigus          483
## 663             564                          Tirtouga          355
## 664             565                        Carracosta          495
## 665             566                            Archen          401
## 666             567                          Archeops          567
## 667             568                          Trubbish          329
## 668             569                          Garbodor          474
## 669             570                             Zorua          330
## 670             571                           Zoroark          510
## 671             572                          Minccino          300
## 672             573                          Cinccino          470
## 673             574                           Gothita          290
## 674             575                         Gothorita          390
## 675             576                        Gothitelle          490
## 676             577                           Solosis          290
## 677             578                           Duosion          370
## 678             579                         Reuniclus          490
## 679             580                          Ducklett          305
## 680             581                            Swanna          473
## 681             582                         Vanillite          305
## 682             583                         Vanillish          395
## 683             584                         Vanilluxe          535
## 684             585                          Deerling          335
## 685             586                          Sawsbuck          475
## 686             587                            Emolga          428
## 687             588                        Karrablast          315
## 688             589                        Escavalier          495
## 689             590                           Foongus          294
## 690             591                         Amoonguss          464
## 691             592                          Frillish          335
## 692             593                         Jellicent          480
## 693             594                         Alomomola          470
## 694             595                            Joltik          319
## 695             596                        Galvantula          472
## 696             597                         Ferroseed          305
## 697             598                        Ferrothorn          489
## 698             599                             Klink          300
## 699             600                             Klang          440
## 700             601                         Klinklang          520
## 701             602                            Tynamo          275
## 702             603                         Eelektrik          405
## 703             604                        Eelektross          515
## 704             605                            Elgyem          335
## 705             606                          Beheeyem          485
## 706             607                           Litwick          275
## 707             608                           Lampent          370
## 708             609                        Chandelure          520
## 709             610                              Axew          320
## 710             611                           Fraxure          410
## 711             612                           Haxorus          540
## 712             613                           Cubchoo          305
## 713             614                           Beartic          505
## 714             615                         Cryogonal          515
## 715             616                           Shelmet          305
## 716             617                          Accelgor          495
## 717             618                          Stunfisk          471
## 718             618                 Galarian Stunfisk          471
## 719             619                           Mienfoo          350
## 720             620                          Mienshao          510
## 721             621                         Druddigon          485
## 722             622                            Golett          303
## 723             623                            Golurk          483
## 724             624                          Pawniard          340
## 725             625                           Bisharp          490
## 726             626                        Bouffalant          490
## 727             627                           Rufflet          350
## 728             628                          Braviary          510
## 729             629                           Vullaby          370
## 730             630                         Mandibuzz          510
## 731             631                           Heatmor          484
## 732             632                            Durant          484
## 733             633                             Deino          300
## 734             634                          Zweilous          420
## 735             635                         Hydreigon          600
## 736             636                          Larvesta          360
## 737             637                         Volcarona          550
## 738             638                          Cobalion          580
## 739             639                         Terrakion          580
## 740             640                          Virizion          580
## 741             641          Tornadus Incarnate Forme          580
## 742             641            Tornadus Therian Forme          580
## 743             642         Thundurus Incarnate Forme          580
## 744             642           Thundurus Therian Forme          580
## 745             643                          Reshiram          680
## 746             644                            Zekrom          680
## 747             645          Landorus Incarnate Forme          600
## 748             645            Landorus Therian Forme          600
## 749             646                            Kyurem          660
## 750             646                      Black Kyurem          700
## 751             646                      White Kyurem          700
## 752             647             Keldeo Ordinary Forme          580
## 753             647             Keldeo Resolute Forme          580
## 754             648               Meloetta Aria Forme          600
## 755             648          Meloetta Pirouette Forme          600
## 756             649                          Genesect          600
## 757             650                           Chespin          313
## 758             651                         Quilladin          405
## 759             652                        Chesnaught          530
## 760             653                          Fennekin          307
## 761             654                           Braixen          409
## 762             655                           Delphox          534
## 763             656                           Froakie          314
## 764             657                         Frogadier          405
## 765             658                          Greninja          530
## 766             658                      Ash-Greninja          640
## 767             659                          Bunnelby          237
## 768             660                         Diggersby          423
## 769             661                        Fletchling          278
## 770             662                       Fletchinder          382
## 771             663                        Talonflame          499
## 772             664                        Scatterbug          200
## 773             665                            Spewpa          213
## 774             666                          Vivillon          411
## 775             667                            Litleo          369
## 776             668                            Pyroar          507
## 777             669                         FlabÃ©bÃ©          303
## 778             670                           Floette          371
## 779             671                           Florges          552
## 780             672                            Skiddo          350
## 781             673                            Gogoat          531
## 782             674                           Pancham          348
## 783             675                           Pangoro          495
## 784             676                           Furfrou          472
## 785             677                            Espurr          355
## 788             679                           Honedge          325
## 789             680                          Doublade          448
## 792             682                          Spritzee          341
## 793             683                        Aromatisse          462
## 794             684                           Swirlix          341
## 795             685                          Slurpuff          480
## 796             686                             Inkay          288
## 797             687                           Malamar          482
## 798             688                           Binacle          306
## 799             689                        Barbaracle          500
## 800             690                            Skrelp          320
## 801             691                          Dragalge          494
## 802             692                         Clauncher          330
## 803             693                         Clawitzer          500
## 804             694                        Helioptile          289
## 805             695                         Heliolisk          481
## 806             696                            Tyrunt          362
## 807             697                         Tyrantrum          521
## 808             698                            Amaura          362
## 809             699                           Aurorus          521
## 810             700                           Sylveon          525
## 811             701                          Hawlucha          500
## 812             702                           Dedenne          431
## 813             703                           Carbink          500
## 814             704                             Goomy          300
## 815             705                           Sliggoo          452
## 816             706                            Goodra          600
## 817             707                            Klefki          470
## 818             708                          Phantump          309
## 819             709                         Trevenant          474
## 820             710            Pumpkaboo Average Size          335
## 824             711            Gourgeist Average Size          494
## 828             712                          Bergmite          304
## 829             713                           Avalugg          514
## 830             714                            Noibat          245
## 831             715                           Noivern          535
## 832             716                           Xerneas          680
## 833             717                           Yveltal          680
## 834             718                 Zygarde 50% Forme          600
## 835             718                 Zygarde 10% Forme          486
## 836             718            Zygarde Complete Forme          708
## 837             719                           Diancie          600
## 838             719                      Mega Diancie          700
## 839             720              Hoopa Hoopa Confined          600
## 840             720               Hoopa Hoopa Unbound          680
## 841             721                         Volcanion          600
## 842             722                            Rowlet          320
## 843             723                           Dartrix          420
## 844             724                         Decidueye          530
## 845             725                            Litten          320
## 846             726                          Torracat          420
## 847             727                        Incineroar          530
## 848             728                           Popplio          320
## 849             729                           Brionne          420
## 850             730                         Primarina          530
## 851             731                           Pikipek          265
## 852             732                          Trumbeak          355
## 853             733                         Toucannon          485
## 854             734                           Yungoos          253
## 855             735                          Gumshoos          418
## 856             736                           Grubbin          300
## 857             737                         Charjabug          400
## 858             738                          Vikavolt          500
## 859             739                        Crabrawler          338
## 860             740                      Crabominable          478
## 861             741              Oricorio Baile Style          476
## 862             741            Oricorio Pom-Pom Style          476
## 863             741               Oricorio Pa&#39;u Style          476
## 864             741              Oricorio Sensu Style          476
## 865             742                          Cutiefly          304
## 866             743                          Ribombee          464
## 867             744                          Rockruff          280
## 869             745              Lycanroc Midday Form          487
## 870             745            Lycanroc Midnight Form          487
## 871             745                Lycanroc Dusk Form          487
## 872             746              Wishiwashi Solo Form          175
## 873             746            Wishiwashi School Form          620
## 874             747                          Mareanie          305
## 875             748                           Toxapex          495
## 876             749                           Mudbray          385
## 877             750                          Mudsdale          500
## 878             751                          Dewpider          269
## 879             752                         Araquanid          454
## 880             753                          Fomantis          250
## 881             754                          Lurantis          480
## 882             755                          Morelull          285
## 883             756                         Shiinotic          405
## 884             757                          Salandit          320
## 885             758                          Salazzle          480
## 886             759                           Stufful          340
## 887             760                            Bewear          500
## 888             761                         Bounsweet          210
## 889             762                           Steenee          290
## 890             763                          Tsareena          510
## 891             764                            Comfey          485
## 892             765                          Oranguru          490
## 893             766                         Passimian          490
## 894             767                            Wimpod          230
## 895             768                         Golisopod          530
## 896             769                         Sandygast          320
## 897             770                         Palossand          480
## 898             771                         Pyukumuku          410
## 899             772                        Type: Null          534
## 900             773                          Silvally          570
## 901             774                Minior Meteor Form          440
## 902             774                  Minior Core Form          500
## 903             775                            Komala          480
## 904             776                        Turtonator          485
## 905             777                        Togedemaru          435
## 906             778                           Mimikyu          476
## 907             779                           Bruxish          475
## 908             780                            Drampa          485
## 909             781                          Dhelmise          517
## 910             782                          Jangmo-o          300
## 911             783                          Hakamo-o          420
## 912             784                           Kommo-o          600
## 913             785                         Tapu Koko          570
## 914             786                         Tapu Lele          570
## 915             787                         Tapu Bulu          570
## 916             788                         Tapu Fini          570
## 917             789                            Cosmog          200
## 918             790                           Cosmoem          400
## 919             791                          Solgaleo          680
## 920             792                            Lunala          680
## 921             793                          Nihilego          570
## 922             794                          Buzzwole          570
## 923             795                         Pheromosa          570
## 924             796                         Xurkitree          570
## 925             797                        Celesteela          570
## 926             798                           Kartana          570
## 927             799                          Guzzlord          570
## 928             800                          Necrozma          600
## 929             800                Dusk Mane Necrozma          680
## 930             800               Dawn Wings Necrozma          680
## 931             800                    Ultra Necrozma          754
## 932             801                          Magearna          600
## 933             802                         Marshadow          600
## 934             803                           Poipole          420
## 935             804                         Naganadel          540
## 936             805                         Stakataka          570
## 937             806                       Blacephalon          570
## 938             807                           Zeraora          600
## 939             808                            Meltan          300
## 940             809                          Melmetal          600
## 941             810                           Grookey          310
## 942             811                          Thwackey          420
## 943             812                         Rillaboom          530
## 944             813                         Scorbunny          310
## 945             814                            Raboot          420
## 946             815                         Cinderace          530
## 947             816                            Sobble          310
## 948             817                          Drizzile          420
## 949             818                          Inteleon          530
## 950             819                           Skwovet          275
## 951             820                          Greedent          460
## 952             821                          Rookidee          245
## 953             822                       Corvisquire          365
## 954             823                       Corviknight          495
## 955             824                           Blipbug          180
## 956             825                           Dottler          335
## 957             826                          Orbeetle          505
## 958             827                            Nickit          245
## 959             828                           Thievul          455
## 960             829                        Gossifleur          250
## 961             830                          Eldegoss          460
## 962             831                            Wooloo          270
## 963             832                           Dubwool          490
## 964             833                           Chewtle          284
## 965             834                           Drednaw          485
## 966             835                            Yamper          270
## 967             836                           Boltund          490
## 968             837                          Rolycoly          240
## 969             838                            Carkol          410
## 970             839                         Coalossal          510
## 971             840                            Applin          260
## 972             841                           Flapple          485
## 973             842                          Appletun          485
## 974             843                         Silicobra          315
## 975             844                        Sandaconda          510
## 976             845                         Cramorant          475
## 977             846                          Arrokuda          280
## 978             847                       Barraskewda          490
## 979             848                             Toxel          242
## 980             849           Toxtricity Low Key Form          502
## 981             849             Toxtricity Amped Form          502
## 982             850                        Sizzlipede          305
## 983             851                       Centiskorch          525
## 984             852                         Clobbopus          310
## 985             853                         Grapploct          480
## 986             854                          Sinistea          308
## 987             855                       Polteageist          508
## 988             856                           Hatenna          265
## 989             857                           Hattrem          370
## 990             858                         Hatterene          510
## 991             859                          Impidimp          265
## 992             860                           Morgrem          370
## 993             861                        Grimmsnarl          510
## 994             862                         Obstagoon          520
## 995             863                        Perrserker          440
## 996             864                           Cursola          510
## 997             865                        Sirfetch&#39;d          507
## 998             866                          Mr. Rime          520
## 999             867                         Runerigus          483
## 1000            868                           Milcery          270
## 1001            869                          Alcremie          495
## 1002            870                           Falinks          470
## 1003            871                        Pincurchin          435
## 1004            872                              Snom          185
## 1005            873                          Frosmoth          475
## 1006            874                       Stonjourner          470
## 1007            875                   Eiscue Ice Face          470
## 1008            875                 Eiscue Noice Face          470
## 1009            876                     Indeedee Male          475
## 1010            876                   Indeedee Female          475
## 1011            877           Morpeko Full Belly Mode          436
## 1012            877               Morpeko Hangry Mode          436
## 1013            878                            Cufant          330
## 1014            879                        Copperajah          500
## 1015            880                         Dracozolt          505
## 1016            881                         Arctozolt          505
## 1017            882                         Dracovish          505
## 1018            883                         Arctovish          505
## 1019            884                         Duraludon          535
## 1020            885                            Dreepy          270
## 1021            886                          Drakloak          410
## 1022            887                         Dragapult          600
## 1023            888              Zacian Crowned Sword          720
## 1024            888       Zacian Hero of Many Battles          670
## 1025            889          Zamazenta Crowned Shield          720
## 1026            889    Zamazenta Hero of Many Battles          670
## 1027            890                         Eternatus          690
##                                                         num design_mean
## 1                                                         1    8.090909
## 2                                                         2    7.545455
## 3                                                         3    5.454545
## 4                                                        3M    6.545455
## 5                                                         4    6.363636
## 6                                                         5    6.454545
## 7                                                         6    8.363636
## 8                                                       6MX    7.090909
## 9                                                       6MY    8.909091
## 10                                                        7    7.909091
## 11                                                        8    7.000000
## 12                                                        9    6.636364
## 13                                                       9M    6.545455
## 14                                                       10    4.636364
## 15                                                       11    3.000000
## 16                                                       12    4.818182
## 17                                                       13    3.636364
## 18                                                       14    3.909091
## 19                                                       15    5.181818
## 20                                                      15M    6.272727
## 21                                                       16    4.636364
## 22                                                       17    5.090909
## 23                                                       18    6.181818
## 24                                                      18M    6.727273
## 25                                                       19    4.636364
## 26                                                      19A    3.272727
## 27                                                       20    3.363636
## 28                                                      20A    3.000000
## 29                                                       21    4.727273
## 30                                                       22    3.909091
## 31                                                       23    3.090909
## 32                                                       24    4.181818
## 33                                                       25    8.727273
## 34                                                      25P    8.909091
## 35                                                       26    7.272727
## 36                                                      26A    7.090909
## 37                                                       27    6.363636
## 38                                                      27A    7.454545
## 39                                                       28    6.909091
## 40                                                      28A    7.909091
## 41                                                       29    4.454545
## 42                                                       30    6.363636
## 43                                                       31    5.636364
## 44                                                       32    5.636364
## 45                                                       33    4.909091
## 46                                                       34    4.818182
## 47                                                       35    6.272727
## 48                                                       36    5.545455
## 49                                                       37    8.181818
## 50                                                      37A    8.909091
## 51                                                       38    8.454545
## 52                                                      38A    9.090909
## 53                                                       39    6.636364
## 54                                                       40    6.909091
## 55                                                       41    3.090909
## 56                                                       42    3.727273
## 57                                                       43    6.727273
## 58                                                       44    3.000000
## 59                                                       45    6.181818
## 60                                                       46    4.363636
## 61                                                       47    3.636364
## 62                                                       48    4.272727
## 63                                                       49    4.909091
## 64                                                       50    4.636364
## 65                                                      50A    4.000000
## 66                                                       51    4.545455
## 67                                                      51A    3.818182
## 68                                                       52    6.090909
## 69                                                      52A    5.909091
## 70                                                      52G    3.272727
## 71                                                       53    6.909091
## 72                                                      53A    3.727273
## 73                                                       54    5.545455
## 74                                                       55    4.727273
## 75                                                       56    4.000000
## 76                                                       57    4.272727
## 77                                                       58    8.454545
## 78                                                       59    6.909091
## 79                                                       60    6.363636
## 80                                                       61    5.818182
## 81                                                       62    5.090909
## 82                                                       63    6.454545
## 83                                                       64    4.727273
## 84                                                       65    4.090909
## 85                                                      65A    5.272727
## 86                                                       66    5.272727
## 87                                                       67    4.454545
## 88                                                       68    5.727273
## 89                                                       69    6.636364
## 90                                                       70    4.000000
## 91                                                       71    4.636364
## 92                                                       72    3.818182
## 93                                                       73    3.727273
## 94                                                       74    3.090909
## 95                                                      74A    3.909091
## 96                                                       75    4.090909
## 97                                                      75A    4.181818
## 98                                                       76    4.272727
## 99                                                      76A    5.454545
## 100                                                      77    7.000000
## 101                                                     77G    8.000000
## 102                                                      78    6.363636
## 103                                                     78G    6.909091
## 104                                                      79    4.181818
## 105                                                      80    4.454545
## 106                                                     80M    4.818182
## 107                                                      81    4.181818
## 108                                                      82    4.636364
## 109                                                      83    6.545455
## 110                                                     83G    5.727273
## 111                                                      84    5.454545
## 112                                                      85    4.181818
## 113                                                      86    7.545455
## 114                                                      87    7.363636
## 115                                                      88    3.181818
## 116                                                     88A    2.909091
## 117                                                      89    2.636364
## 118                                                     89A    3.363636
## 119                                                      90    4.454545
## 120                                                      91    4.727273
## 121                                                      92    2.818182
## 122                                                      93    5.181818
## 123                                                      94    5.363636
## 124                                                     94A    5.181818
## 125                                                      95    4.000000
## 126                                                      96    3.909091
## 127                                                      97    2.636364
## 128                                                      98    3.727273
## 129                                                      99    3.727273
## 130                                                     100    2.818182
## 131                                                     101    3.090909
## 132                                                     102    3.545455
## 133                                                     103    4.090909
## 134                                                    103A    4.818182
## 135                                                     104    6.545455
## 136                                                     105    4.818182
## 137                                                    105A    7.545455
## 138                                                     106    4.181818
## 139                                                     107    5.909091
## 140                                                     108    4.727273
## 141                                                     109    3.363636
## 142                                                     110    3.000000
## 143                                                    110G    5.000000
## 144                                                     111    5.090909
## 145                                                     112    5.727273
## 146                                                     113    6.181818
## 147                                                     114    4.272727
## 148                                                     115    6.181818
## 149                                                    115M    5.727273
## 150                                                     116    6.000000
## 151                                                     117    5.090909
## 152                                                     118    5.818182
## 153                                                     119    5.090909
## 154                                                     120    5.181818
## 155                                                     121    5.181818
## 156                                                     122    4.272727
## 157                                                    122G    4.818182
## 158                                                     123    7.000000
## 159                                                     124    2.181818
## 160                                                     125    4.727273
## 161                                                     126    5.818182
## 162                                                     127    3.818182
## 163                                                    127M    3.090909
## 164                                                     128    4.727273
## 165                                                     129    4.909091
## 166                                                     130    6.363636
## 167                                                    130M    6.545455
## 168                                                     131    7.909091
## 169                                                     132    7.909091
## 170                                                     133    8.272727
## 171                                                    133P    8.818182
## 172                                                     134    8.272727
## 173                                                     135    7.727273
## 174                                                     136    7.454545
## 175                                                     137    3.727273
## 176                                                     138    6.363636
## 177                                                     139    3.818182
## 178                                                     140    4.000000
## 179                                                     141    4.636364
## 180                                                     142    4.454545
## 181                                                    142M    6.000000
## 182                                                     143    7.090909
## 183                                                     144    7.363636
## 184                                                     145    5.181818
## 185                                                     146    6.727273
## 186                                                     147    7.272727
## 187                                                     148    8.363636
## 188                                                     149    7.818182
## 189                                                     150    6.909091
## 190                                                   150MX    6.000000
## 191                                                   150MY    7.454545
## 192                                                     151    8.000000
## 193                                                     152    7.272727
## 194                                                     153    6.727273
## 195                                                     154    7.363636
## 196                                                     155    6.545455
## 197                                                     156    6.181818
## 198                                                     157    6.181818
## 199                                                     158    6.727273
## 200                                                     159    5.454545
## 201                                                     160    6.272727
## 202                                                     161    6.272727
## 203                                                     162    7.000000
## 204                                                     163    5.454545
## 205                                                     164    5.454545
## 206                                                     165    5.636364
## 207                                                     166    6.909091
## 208                                                     167    5.090909
## 209                                                     168    4.909091
## 210                                                     169    5.636364
## 211                                                     170    5.818182
## 212                                                     171    6.727273
## 213                                                     172    7.272727
## 214                                                     173    7.000000
## 215                                                     174    7.636364
## 216                                                     175    6.545455
## 217                                                     176    6.727273
## 218                                                     177    5.272727
## 219                                                     178    5.363636
## 220                                                     179    6.909091
## 221                                                     180    6.727273
## 222                                                     181    7.000000
## 223                                                    181M    7.363636
## 224                                                     182    6.454545
## 225                                                     183    6.545455
## 226                                                     184    5.909091
## 227                                                     185    5.909091
## 228                                                     186    6.181818
## 229                                                     187    6.363636
## 230                                                     188    6.181818
## 231                                                     189    6.000000
## 232                                                     190    5.454545
## 233                                                     191    6.181818
## 234                                                     192    4.727273
## 235                                                     193    4.818182
## 236                                                     194    6.181818
## 237                                                     195    6.000000
## 238                                                     196    7.545455
## 239                                                     197    7.454545
## 240                                                     198    4.909091
## 241                                                     199    6.272727
## 242                                                     200    6.181818
## 243                                                     201    5.909091
## 244                                                     202    5.181818
## 245                                                     203    6.818182
## 246                                                     204    3.727273
## 247                                                     205    5.181818
## 248                                                     206    5.727273
## 249                                                     207    4.818182
## 250                                                     208    7.000000
## 251                                                    208M    7.727273
## 252                                                     209    5.545455
## 253                                                     210    5.454545
## 254                                                     211    5.181818
## 255                                                     212    7.727273
## 256                                                    212M    7.909091
## 257                                                     213    6.090909
## 258                                                     214    6.545455
## 259                                                    214M    6.181818
## 260                                                     215    6.545455
## 261                                                     216    6.272727
## 262                                                     217    6.818182
## 263                                                     218    4.272727
## 264                                                     219    4.909091
## 265                                                     220    5.727273
## 266                                                     221    5.181818
## 267                                                     222    5.909091
## 268                                                    222G    5.363636
## 269                                                     223    4.909091
## 270                                                     224    6.545455
## 271                                                     225    6.272727
## 272                                                     226    7.090909
## 273                                                     227    6.454545
## 274                                                     228    4.909091
## 275                                                     229    6.909091
## 276                                                    229M    8.181818
## 277                                                     230    5.909091
## 278                                                     231    6.727273
## 279                                                     232    4.727273
## 280                                                     233    5.909091
## 281                                                     234    6.090909
## 282                                                     235    6.636364
## 283                                                     236    6.363636
## 284                                                     237    5.454545
## 285                                                     238    5.636364
## 286                                                     239    6.363636
## 287                                                     240    6.181818
## 288                                                     241    5.727273
## 289                                                     242    7.272727
## 290                                                     243    6.272727
## 291                                                     244    7.181818
## 292                                                     245    6.818182
## 293                                                     246    4.727273
## 294                                                     247    5.454545
## 295                                                     248    6.000000
## 296                                                    248M    6.727273
## 297                                                     249    5.545455
## 298                                                     250    7.727273
## 299                                                     251    8.090909
## 300                                                     252    6.222222
## 301                                                     253    6.333333
## 302                                                     254    6.333333
## 303                                                    254M    7.222222
## 304                                                     255    8.222222
## 305                                                     256    6.666667
## 306                                                     257    7.333333
## 307                                                    257M    7.888889
## 308                                                     258    7.666667
## 309                                                     259    7.222222
## 310                                                     260    6.444444
## 311                                                    260M    6.555556
## 312                                                     261    6.222222
## 313                                                     262    7.888889
## 314                                                     263    5.222222
## 315                                                    263M    6.666667
## 316                                                     264    6.000000
## 317                                                    264M    5.222222
## 318                                                     265    6.111111
## 319                                                     266    5.222222
## 320                                                     267    5.777778
## 321                                                     268    4.000000
## 322                                                     269    4.888889
## 323                                                     270    5.111111
## 324                                                     271    4.111111
## 325                                                     272    5.666667
## 326                                                     273    5.111111
## 327                                                     274    6.222222
## 328                                                     275    5.666667
## 329                                                     276    5.555556
## 330                                                     277    5.222222
## 331                                                     278    6.222222
## 332                                                     279    4.888889
## 333                                                     280    6.666667
## 334                                                     281    6.222222
## 335                                                     282    7.555556
## 336                                                    282M    8.888889
## 337                                                     283    6.888889
## 338                                                     284    7.222222
## 339                                                     285    4.666667
## 340                                                     286    6.555556
## 341                                                     287    5.333333
## 342                                                     288    4.444444
## 343                                                     289    5.000000
## 344                                                     290    5.222222
## 345                                                     291    5.111111
## 346                                                     292    5.888889
## 347                                                     293    4.777778
## 348                                                     294    4.777778
## 349                                                     295    5.111111
## 350                                                     296    6.000000
## 351                                                     297    5.333333
## 352                                                     298    7.333333
## 353                                                     299    5.222222
## 354                                                     300    7.111111
## 355                                                     301    8.111111
## 356                                                     302    4.777778
## 357                                                    302M    6.222222
## 358                                                     303    7.000000
## 359                                                    303M    7.666667
## 360                                                     304    5.888889
## 361                                                     305    5.777778
## 362                                                     306    7.000000
## 363                                                    306M    8.222222
## 364                                                     307    6.333333
## 365                                                     308    5.777778
## 366                                                    308M    6.666667
## 367                                                     309    4.555556
## 368                                                     310    8.000000
## 369                                                    310M    7.222222
## 370                                                     311    6.666667
## 371                                                     312    7.555556
## 372                                                     313    5.888889
## 373                                                     314    4.888889
## 374                                                     315    7.555556
## 375                                                     316    5.111111
## 376                                                     317    6.111111
## 377                                                     318    5.333333
## 378                                                     319    6.777778
## 379                                                    319M    8.555556
## 380                                                     320    6.222222
## 381                                                     321    7.222222
## 382                                                     322    6.222222
## 383                                                     323    6.000000
## 384                                                    323M    6.222222
## 385                                                     324    6.444444
## 386                                                     325    7.222222
## 387                                                     326    4.555556
## 388                                                     327    6.222222
## 389                                                     328    6.111111
## 390                                                     329    4.000000
## 391                                                     330    6.222222
## 392                                                     331    5.777778
## 393                                                     332    4.000000
## 394                                                     333    7.222222
## 395                                                     334    8.444444
## 396                                                    334M    8.333333
## 397                                                     335    6.555556
## 398                                                     336    4.111111
## 399                                                     337    5.000000
## 400                                                     338    5.777778
## 401                                                     339    4.222222
## 402                                                     340    5.222222
## 403                                                     341    3.444444
## 404                                                     342    5.222222
## 405                                                     343    3.555556
## 406                                                     344    5.555556
## 407                                                     345    4.333333
## 408                                                     346    5.222222
## 409                                                     347    5.111111
## 410                                                     348    6.111111
## 411                                                     349    4.444444
## 412                                                     350    7.777778
## 413                                                     351    8.555556
## 417                                                     352    5.666667
## 418                                                     353    6.000000
## 419                                                     354    4.555556
## 420                                                    354M    6.222222
## 421                                                     355    5.444444
## 422                                                     356    5.333333
## 423                                                     357    7.333333
## 424                                                     358    5.777778
## 425                                                     359    7.888889
## 426                                                    359M    8.666667
## 427                                                     360    6.777778
## 428                                                     361    5.444444
## 429                                                     362    5.222222
## 430                                                    362M    6.444444
## 431                                                     363    7.666667
## 432                                                     364    7.666667
## 433                                                     365    6.777778
## 434                                                     366    6.666667
## 435                                                     367    3.777778
## 436                                                     368    5.444444
## 437                                                     369    4.222222
## 438                                                     370    5.444444
## 439                                                     371    5.666667
## 440                                                     372    4.555556
## 441                                                     373    8.222222
## 442                                                    373M    8.555556
## 443                                                     374    5.333333
## 444                                                     375    7.000000
## 445                                                     376    8.111111
## 446                                                    376M    7.333333
## 447                                                     377    7.444444
## 448                                                     378    7.333333
## 449                                                     379    7.666667
## 450                                                     380    7.555556
## 451                                                    380M    7.888889
## 452                                                     381    8.222222
## 453                                                    381M    8.222222
## 454                                                     382    8.666667
## 455                                                    382P    9.666667
## 456                                                     383    8.333333
## 457                                                    383M    7.888889
## 458                                                     384    8.111111
## 459                                                    384M    9.777778
## 460                                                     385    8.333333
## 461                                                     386    7.222222
## 462                                                    386A    7.888889
## 463                                                    386D    7.000000
## 464                                                    386S    7.333333
## 465                                                     387    7.666667
## 466                                                     388    6.888889
## 467                                                     389    7.777778
## 468                                                     390    7.111111
## 469                                                     391    7.000000
## 470                                                     392    7.777778
## 471                                                     393    8.000000
## 472                                                     394    7.777778
## 473                                                     395    8.222222
## 474                                                     396    6.111111
## 475                                                     397    6.000000
## 476                                                     398    6.777778
## 477                                                     399    6.222222
## 478                                                     400    5.555556
## 479                                                     401    6.000000
## 480                                                     402    5.888889
## 481                                                     403    7.000000
## 482                                                     404    6.444444
## 483                                                     405    7.888889
## 484                                                     406    6.666667
## 485                                                     407    6.666667
## 486                                                     408    6.444444
## 487                                                     409    7.333333
## 488                                                     410    5.888889
## 489                                                     411    5.777778
## 490                                                     412    5.333333
## 491                                                     413    6.111111
## 492                                                     413    5.333333
## 493                                                     413    5.888889
## 494                                                     414    5.777778
## 495                                                     415    6.444444
## 496                                                     416    6.000000
## 497                                                     417    7.666667
## 498                                                     418    7.555556
## 499                                                     419    7.000000
## 500                                                     420    6.777778
## 501                                                     421    7.111111
## 502                                                     422    6.666667
## 503                                                     423    6.444444
## 504                                                     424    6.888889
## 505                                                     425    7.000000
## 506                                                     426    6.666667
## 507                                                     427    6.444444
## 508                                                     428    7.333333
## 509                                                    428M    8.111111
## 510                                                     429    7.333333
## 511                                                     430    7.222222
## 512                                                     431    6.555556
## 513                                                     432    5.000000
## 514                                                     433    6.111111
## 515                                                     434    6.111111
## 516                                                     435    6.777778
## 517                                                     436    5.222222
## 518                                                     437    6.111111
## 519                                                     438    6.666667
## 520                                                     439    6.666667
## 521                                                     440    6.111111
## 522                                                     441    6.777778
## 523                                                     442    6.555556
## 524                                                     443    6.777778
## 525                                                     444    6.222222
## 526                                                     445    7.333333
## 527                                                    445M    7.333333
## 528                                                     446    6.555556
## 529                                                     447    6.333333
## 530                                                     448    7.666667
## 531                                                    448M    7.777778
## 532                                                     449    4.666667
## 533                                                     450    5.111111
## 534                                                     451    6.333333
## 535                                                     452    5.555556
## 536                                                     453    6.333333
## 537                                                     454    6.888889
## 538                                                     455    5.555556
## 539                                                     456    6.000000
## 540                                                     457    6.000000
## 541                                                     458    6.111111
## 542                                                     459    6.666667
## 543                                                     460    6.111111
## 544                                                    460M    7.777778
## 545                                                     461    7.888889
## 546                                                     462    6.555556
## 547                                                     463    5.222222
## 548                                                     464    6.444444
## 549                                                     465    5.777778
## 550                                                     466    7.333333
## 551                                                     467    6.777778
## 552                                                     468    6.666667
## 553                                                     469    6.777778
## 554                                                     470    7.333333
## 555                                                     471    7.555556
## 556                                                     472    5.555556
## 557                                                     473    6.111111
## 558                                                     474    6.222222
## 559                                                     475    7.111111
## 561                                                     476    5.333333
## 562                                                     477    7.333333
## 563                                                     478    7.333333
## 564                                                     479    7.111111
## 565                                                    479H    6.333333
## 566                                                    479W    6.333333
## 567                                                    479F    6.444444
## 568                                                   479FA    6.777778
## 569                                                    479M    6.444444
## 570                                                     480    6.666667
## 571                                                     481    7.111111
## 572                                                     482    7.888889
## 573                                                     483    7.666667
## 574                                                     484    8.666667
## 575                                                     485    5.444444
## 576                                                     486    7.777778
## 577                                                     487    7.333333
## 578                                                    487O    7.666667
## 579                                                     488    7.777778
## 580                                                     489    6.222222
## 581                                                     490    7.666667
## 582                                                     491    8.000000
## 583                                                     492    7.666667
## 584                                                    492S    7.333333
## 585                                                     493    7.444444
## 586                                                     494    7.666667
## 587                                                     495    6.727273
## 588                                                     496    7.181818
## 589                                                     497    7.000000
## 590                                                     498    8.000000
## 591                                                     499    5.818182
## 592                                                     500    5.818182
## 593                                                     501    7.181818
## 594                                                     502    6.272727
## 595                                                     503    7.363636
## 596                                                     504    4.454545
## 597                                                     505    4.545455
## 598                                                     506    6.818182
## 599                                                     507    6.181818
## 600                                                     508    5.909091
## 601                                                     509    6.727273
## 602                                                     510    7.090909
## 603                                                     511    5.727273
## 604                                                     512    5.363636
## 605                                                     513    5.909091
## 606                                                     514    5.727273
## 607                                                     515    6.545455
## 608                                                     516    6.090909
## 609                                                     517    6.545455
## 610                                                     518    6.000000
## 611                                                     519    4.545455
## 612                                                     520    5.545455
## 613                                                     521    6.181818
## 614                                                     522    7.818182
## 615                                                     523    7.181818
## 616                                                     524    4.636364
## 617                                                     525    5.090909
## 618                                                     526    5.909091
## 619                                                     527    5.636364
## 620                                                     528    5.090909
## 621                                                     529    4.818182
## 622                                                     530    5.363636
## 623                                                     531    6.272727
## 624                                                    531M    6.727273
## 625                                                     532    5.454545
## 626                                                     533    3.818182
## 627                                                     534    4.000000
## 628                                                     535    5.818182
## 629                                                     536    4.454545
## 630                                                     537    5.000000
## 631                                                     538    4.000000
## 632                                                     539    3.272727
## 633                                                     540    6.727273
## 634                                                     541    6.272727
## 635                                                     542    5.363636
## 636                                                     543    3.909091
## 637                                                     544    4.454545
## 638                                                     545    5.000000
## 639                                                     546    6.272727
## 640                                                     547    6.636364
## 641                                                     548    6.545455
## 642                                                     549    8.090909
## 643                                                     550    3.181818
## 644                                                    550B    3.545455
## 645                                                     551    6.181818
## 646                                                     552    5.363636
## 647                                                     553    5.727273
## 648                                                     554    5.818182
## 649                                                    554G    5.909091
## 650                                                     555    5.272727
## 651                                                    555Z    5.090909
## 652                                                    555G    5.363636
## 653                                                   555GZ    5.454545
## 654                                                     556    6.363636
## 655                                                     557    7.363636
## 656                                                     558    4.909091
## 657                                                     559    5.272727
## 658                                                     560    4.454545
## 659                                                     561    6.909091
## 660                                                     562    4.727273
## 661                                                    562G    5.909091
## 662                                                     563    5.272727
## 663                                                     564    5.545455
## 664                                                     465    4.909091
## 665                                                     566    4.818182
## 666                                                     567    6.090909
## 667                                                     568    6.000000
## 668                                                     569    5.090909
## 669                                                     570    7.636364
## 670                                                     571    6.363636
## 671                                                     572    6.727273
## 672                                                     573    7.272727
## 673                                                     574    5.909091
## 674                                                     575    6.272727
## 675                                                     576    4.727273
## 676                                                     577    7.636364
## 677                                                     578    7.636364
## 678                                                     579    7.909091
## 679                                                     580    6.545455
## 680                                                     581    5.272727
## 681                                                     582    6.363636
## 682                                                     583    5.090909
## 683                                                     584    6.181818
## 684                                                     585    7.818182
## 685                                                     586    6.818182
## 686                                                     587    7.909091
## 687                                                     588    5.454545
## 688                                                     589    4.636364
## 689                                                     590    6.727273
## 690                                                     591    5.545455
## 691                                                     592    5.636364
## 692                                                     593    6.636364
## 693                                                     594    4.636364
## 694                                                     595    6.818182
## 695                                                     596    6.545455
## 696                                                     597    4.909091
## 697                                                     598    5.636364
## 698                                                     599    4.454545
## 699                                                     600    5.181818
## 700                                                     601    4.909091
## 701                                                     602    5.272727
## 702                                                     603    4.272727
## 703                                                     604    4.727273
## 704                                                     605    4.636364
## 705                                                     606    4.454545
## 706                                                     607    6.909091
## 707                                                     608    7.636364
## 708                                                     609    7.909091
## 709                                                     610    7.909091
## 710                                                     611    5.272727
## 711                                                     612    5.454545
## 712                                                     613    7.363636
## 713                                                     614    5.909091
## 714                                                     615    4.000000
## 715                                                     616    4.909091
## 716                                                     617    4.090909
## 717                                                     618    4.818182
## 718                                                    618G    4.818182
## 719                                                     619    5.818182
## 720                                                     620    6.363636
## 721                                                     621    4.000000
## 722                                                     622    5.272727
## 723                                                     623    6.636364
## 724                                                     624    4.545455
## 725                                                     625    5.545455
## 726                                                     626    6.090909
## 727                                                     627    5.545455
## 728                                                     628    5.272727
## 729                                                     629    3.727273
## 730                                                     630    3.727273
## 731                                                     631    4.363636
## 732                                                     632    5.363636
## 733                                                     633    6.181818
## 734                                                     634    5.909091
## 735                                                     635    6.363636
## 736                                                     636    4.909091
## 737                                                     637    7.454545
## 738                                                     638    5.818182
## 739                                                     639    5.272727
## 740                                                     640    7.454545
## 741                                                     641    5.181818
## 742                                                    641T    4.909091
## 743                                                     642    5.000000
## 744                                                    642T    5.363636
## 745                                                     643    7.363636
## 746                                                     644    7.000000
## 747                                                     645    4.727273
## 748                                                    645T    4.727273
## 749                                                     646    5.181818
## 750                                                    646B    5.909091
## 751                                                    646W    6.181818
## 752                                                     647    6.909091
## 753                                                    647R    7.909091
## 754                                                     648    8.000000
## 755                                                    448P    8.000000
## 756                                                     449    4.272727
## 757                                                     650    7.375000
## 758                                                     651    6.250000
## 759                                                     652    7.875000
## 760                                                     653    7.625000
## 761                                                     654    7.625000
## 762                                                     655    8.625000
## 763                                                     656    6.250000
## 764                                                     657    6.500000
## 765                                                     658    9.125000
## 766                                                    658A    8.250000
## 767                                                     659    6.125000
## 768                                                     660    6.375000
## 769                                                     661    6.500000
## 770                                                     662    6.875000
## 771                                                     663    8.000000
## 772                                                     664    4.625000
## 773                                                     665    6.000000
## 774                                                     666    6.875000
## 775                                                     667    6.125000
## 776                                                     668    8.625000
## 777                                                     669    5.750000
## 778                                                     670    6.500000
## 779                                                     671    6.625000
## 780                                                     672    5.000000
## 781                                                     673    6.500000
## 782                                                     674    6.625000
## 783                                                     675    6.375000
## 784                                                     676    5.500000
## 785                                                     677    6.750000
## 788                                                     679    4.875000
## 789                                                     680    6.125000
## 792                                                     682    6.000000
## 793                                                     683    6.250000
## 794                                                     684    5.250000
## 795                                                     685    4.750000
## 796                                                     686    5.750000
## 797                                                     687    5.500000
## 798                                                     688    5.500000
## 799                                                     689    7.500000
## 800                                                     690    6.250000
## 801                                                     691    8.000000
## 802                                                     692    5.125000
## 803                                                     693    6.000000
## 804                                                     693    6.750000
## 805                                                     695    6.875000
## 806                                                     696    8.000000
## 807                                                     697    7.875000
## 808                                                     698    8.000000
## 809                                                     699    9.000000
## 810  700. How would you rate this pokemon&#39;s overall design?    8.625000
## 811                                                     701    7.625000
## 812                                                     702    5.750000
## 813                                                     703    6.250000
## 814                                                     704    5.875000
## 815                                                     705    5.750000
## 816                                                     706    7.250000
## 817                                                     707    5.625000
## 818                                                     708    6.125000
## 819                                                     709    6.625000
## 820                                                     710    5.000000
## 824                                                     711    4.875000
## 828                                                     712    5.750000
## 829                                                     713    4.625000
## 830                                                     714    7.875000
## 831                                                     715    7.625000
## 832                                                     716    8.375000
## 833                                                     717    8.000000
## 834                                                    718F    7.125000
## 835                                                    718T    5.625000
## 836                                                    718C    7.125000
## 837                                                     719    6.500000
## 838                                                    719M    8.000000
## 839                                                     720    6.250000
## 840                                                    720U    6.625000
## 841                                                     721    7.625000
## 842                                                     722    8.400000
## 843                                                     723    6.400000
## 844                                                     724    6.700000
## 845                                                     725    7.400000
## 846                                                     726    7.600000
## 847                                                     727    7.300000
## 848                                                     728    7.800000
## 849                                                     729    8.000000
## 850                                                     730    8.900000
## 851                                                     731    7.900000
## 852                                                     732    6.500000
## 853                                                     733    7.800000
## 854                                                     734    7.700000
## 855                                                     735    3.900000
## 856                                                     736    7.100000
## 857                                                     737    4.600000
## 858                                                     738    5.500000
## 859                                                     739    5.700000
## 860                                                     740    4.100000
## 861                                                    741B    6.800000
## 862                                                    741P    8.100000
## 863                                                   741PA    7.900000
## 864                                                    741S    7.300000
## 865                                                     742    6.500000
## 866                                                     743    7.600000
## 867                                                     744    8.600000
## 869                                                     745    8.100000
## 870                                                    745M    7.900000
## 871                                                    745D    7.900000
## 872                                                     746    5.100000
## 873                                                    746S    3.900000
## 874                                                     747    4.800000
## 875                                                     748    5.700000
## 876                                                     749    6.600000
## 877                                                     750    7.300000
## 878                                                     751    5.700000
## 879                                                     752    6.600000
## 880                                                     753    8.200000
## 881                                                     754    7.500000
## 882                                                     755    6.500000
## 883                                                     756    6.500000
## 884                                                     757    5.600000
## 885                                                     758    6.800000
## 886                                                     759    7.200000
## 887                                                     760    7.200000
## 888                                                     761    6.600000
## 889                                                     762    7.200000
## 890                                                     763    7.600000
## 891                                                     764    8.200000
## 892                                                     765    4.800000
## 893                                                     766    7.100000
## 894                                                     767    5.500000
## 895                                                     768    7.200000
## 896                                                     769    4.900000
## 897                                                     770    5.200000
## 898                                                     771    6.100000
## 899                                                     772    7.300000
## 900                                                     773    8.100000
## 901                                                     774    4.900000
## 902                                                    774C    7.300000
## 903                                                     775    8.100000
## 904                                                     776    6.200000
## 905                                                     777    6.600000
## 906                                                     778    8.100000
## 907                                                     779    3.700000
## 908                                                     780    7.100000
## 909                                                     781    6.800000
## 910                                                     782    7.300000
## 911                                                     783    6.600000
## 912                                                     784    8.500000
## 913                                                     785    7.900000
## 914                                                     786    7.700000
## 915                                                     787    6.600000
## 916                                                     788    8.000000
## 917                                                     789    8.100000
## 918                                                     790    8.800000
## 919                                                     791    9.700000
## 920                                                     792    9.200000
## 921                                                     793    6.800000
## 922                                                     794    6.900000
## 923                                                     795    7.900000
## 924                                                     796    6.800000
## 925                                                     797    5.500000
## 926                                                     798    8.100000
## 927                                                     799    7.400000
## 928                                                     800    6.500000
## 929                                                   800DU    8.500000
## 930                                                   800DA    8.700000
## 931                                                    800U    8.600000
## 932                                                     801    7.000000
## 933                                                     802    7.400000
## 934                                                     803    7.900000
## 935                                                     804    7.400000
## 936                                                     805    5.100000
## 937                                                     806    8.200000
## 938                                                     807    7.700000
## 939                                                     808    6.500000
## 940                                                     809    6.700000
## 941                                                     810    8.625000
## 942                                                     811    8.000000
## 943                                                     812    7.750000
## 944                                                     813    8.625000
## 945                                                     814    7.250000
## 946                                                     815    7.625000
## 947                                                     816    8.000000
## 948                                                     817    6.125000
## 949                                                     818    6.375000
## 950                                                     819    7.875000
## 951                                                     820    7.750000
## 952                                                     821    6.875000
## 953                                                     822    6.375000
## 954                                                     823    8.500000
## 955                                                     824    6.250000
## 956                                                     825    7.000000
## 957                                                     826    6.500000
## 958                                                     827    7.625000
## 959                                                     828    7.500000
## 960                                                     829    7.750000
## 961                                                     830    7.750000
## 962                                                     831    7.500000
## 963                                                     832    6.875000
## 964                                                     833    6.375000
## 965                                                     834    7.375000
## 966                                                     835    8.500000
## 967                                                     836    8.625000
## 968                                                     837    5.625000
## 969                                                     838    5.625000
## 970                                                     839    6.500000
## 971                                                     840    6.875000
## 972                                                     841    6.000000
## 973                                                     842    8.500000
## 974                                                     843    5.750000
## 975                                                     844    5.375000
## 976                                                     845    5.375000
## 977                                                     846    5.250000
## 978                                                     847    4.625000
## 979                                                     848    7.250000
## 980                                                    849L    6.750000
## 981                                                    849A    6.000000
## 982                                                     850    5.750000
## 983                                                     851    6.750000
## 984                                                     852    7.375000
## 985                                                     853    6.375000
## 986                                                     854    8.250000
## 987                                                     855    7.875000
## 988                                                     856    8.125000
## 989                                                     857    7.875000
## 990                                                     858    7.750000
## 991                                                     859    5.875000
## 992                                                     860    6.000000
## 993                                                     861    6.625000
## 994                                                     862    7.875000
## 995                                                     863    6.125000
## 996                                                     864    6.000000
## 997                                                     865    7.375000
## 998                                                     866    6.750000
## 999                                                     867    5.500000
## 1000                                                    868    7.125000
## 1001                                                    869    8.875000
## 1002                                                    870    8.000000
## 1003                                                    871    5.625000
## 1004                                                    872    7.625000
## 1005                                                    873    8.250000
## 1006                                                    874    7.000000
## 1007                                                   875I    7.000000
## 1008                                                   875N    7.250000
## 1009                                                   876M    7.875000
## 1010                                                   876F    8.000000
## 1011                                                    877    7.750000
## 1012                                                   877H    7.750000
## 1013                                                    878    7.875000
## 1014                                                    879    7.375000
## 1015                                                    880    7.250000
## 1016                                                    881    6.500000
## 1017                                                    882    5.500000
## 1018                                                    883    5.625000
## 1019                                                    884    7.250000
## 1020                                                    885    5.625000
## 1021                                                    886    5.750000
## 1022                                                    887    5.750000
## 1023                                                    888    8.750000
## 1024                                                   888C    9.625000
## 1025                                                    889    9.250000
## 1026                                                   889C    8.500000
## 1027                                                    890    7.500000</code></pre>
<p>Finally, we can now do some modeling. Let’s first checkout the relationship between our two variables.</p>
<pre class="r"><code>ggplot(pokemon_design_vs_points, aes(x= design_mean, y = total_points)) +
  geom_point(shape= 19, size= 2, color = &quot;orange1&quot;, alpha = .5)+
  theme_minimal()+
  theme(legend.position = &quot;none&quot;,
       text = element_text(family = &quot;Georgia&quot;))</code></pre>
<p><img src="06--Chapter-5_files/figure-html/unnamed-chunk-11-1.png" width="672" /></p>
<p>Although it isn’t a perfect linear relationship, it seems mostly fine.</p>
<p>Next, we will build our model.</p>
<pre class="r"><code>pokemon_design_vs_points_fit &lt;- lm(total_points ~ design_mean, data = pokemon_design_vs_points)
summary(pokemon_design_vs_points_fit)</code></pre>
<pre><code>## 
## Call:
## lm(formula = total_points ~ design_mean, data = pokemon_design_vs_points)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -285.68  -95.92   16.03   82.03  349.58 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  281.780     17.296   16.29   &lt;2e-16 ***
## design_mean   24.774      2.702    9.17   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 115.6 on 1010 degrees of freedom
## Multiple R-squared:  0.07685,    Adjusted R-squared:  0.07594 
## F-statistic: 84.08 on 1 and 1010 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Design seems to be very statistically correlated with stat total. But only about 7.7 percent of the variation in stat total is accounted for by the variation in design mean.</p>
<p>Let’s make sure our model does not violate linear regression assumptions.</p>
<pre class="r"><code>#Checking for Normality
residuals(pokemon_design_vs_points_fit )</code></pre>
<pre class="r"><code>qqnorm(residuals(pokemon_design_vs_points_fit ), col= &quot;orange1&quot; )
qqline(residuals(pokemon_design_vs_points_fit ))</code></pre>
<p><img src="06--Chapter-5_files/figure-html/unnamed-chunk-14-1.png" width="672" /></p>
<pre class="r"><code>#Checking for Constant Conditional SDs and Linearity
plot(fitted(pokemon_design_vs_points_fit),resid(pokemon_design_vs_points_fit), col= &quot;orange1&quot;, pch= 19)
abline(h=0) </code></pre>
<p><img src="06--Chapter-5_files/figure-html/unnamed-chunk-15-1.png" width="672" /></p>
<p>The constant conditional SDs and linearity assumption seem to be okay. However the normality assumption seems to have been violated according to the QQ plot. What we are probably seeing is a distribution that is more narrow than the expected normal distribution. What might be causing this is the fact that the Pokemon only received 8-11 ratings which probably affected the mean design scores and consequently the distribution.</p>
<p>Let’s get to the plotting:</p>
<pre class="r"><code>visreg(pokemon_design_vs_points_fit, &quot;design_mean&quot;, gg= TRUE, 
       line= list(col =&quot;orange2&quot;),
       xlab = &quot;Mean Design Score&quot;, 
       ylab = &quot;Stat Total&quot;,
       fill = list(col = &quot;grey85&quot;))+ 
  theme_bw()+
  labs(title = &quot;Design Rating vs Stat Total Regression&quot;)+
  theme(text = element_text(family = &quot;Georgia&quot;),
        plot.title = element_text(size = 13, margin(b = 10), hjust = 0.5, family = &quot;Georgia&quot;))</code></pre>
<p><img src="06--Chapter-5_files/figure-html/unnamed-chunk-16-1.png" width="672" /></p>
<p>As we can see, there is a significant correlation between a Pokemon’s design and its stat total. As stated above, one significant caveat to these findings was the amount of survey participants. Only 8-11 participants submitted responses meaning the “design means” may not have been the best representations of the public’s opinion on Pokemon designs. To improve this study, at least 20-25 survey participants would be needed. Nevertheless, these results do show us an interesting feature of Pokemon: Gamefreak may be putting more effort into designing their stronger Pokemon.</p>
</div>

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">


<div class = "footer">
  <div class= "footer-container bin1"> 
    <h3>Cedric's Projects</h3>
    <div class= "footer-icons">
      <a href="https://github.com/larylc" class="fa fa-github"></a>
      <a href="https://www.linkedin.com/in/cedric-lary-1281b01a2/" class="fab fa-linkedin"></a>
      <a href="https://cedriclary.netlify.app/" class="fas fa-user"></a>


      
    </div>
  </div>
    <div class= "footer-container bin2">  
      <p>If you have any questions concerning these projects or my process please feel free to contact me. </p>
    </div>


</div>



</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
