---
title: ""
pagetitle: Cedric's Data Science Projects
html_document:
    css: "style.css"
---

```{r setup, include=FALSE}
htmltools::tagList(rmarkdown::html_dependency_font_awesome())
```

<div class= "main">

<div class = "article article2">

<div id = "line"></div>
<div class = "section section1">

### Welcome to my Archived Project Website! 

This is where I posted my first projects <b>(2018-2022)</b> in their entirety. These projects were formatted so that readers were  <b>1)</b> <p class = "reasons"> taken through my data science thinking process</p> and <b> 2)</b> <p class = "reasons">provided with all of the technical tools I used for these projects. <b>This site is no longer being maintained.</b></p> 


For a more detailed summary of the projects please visit my [GitHub page](https://github.com/larylc/Independent-Projects-).

For more information about my current skill set please visit my [personal website](https://cedriclary.netlify.app/).

</div>

<div id = "line"></div>


<div class = "section section2">
### Project Descriptions 

<div id= "menu1">
<div class= "dropdown dropdown1">
<button class= "drop-button">Major Projects</button>
<details>
<summary><b> Project 1: </b> Summer Research Project (2018) </summary>
<a href= "https://larylc.github.io/Independent-Projects-/Summer-Research-2018-Markdown.html">Investigated how movement affects forked fungus beetle social network position.</a> 
</details>
<details>
<summary><b> Project 2:</b> Exploratory Pokemon Analysis (2020) </summary>
<a href= "https://larylc.github.io/Independent-Projects-/pokemon-project-2020.html" >Explored data visualization using Pokemon gaming data.</a> 
</details>
<details>
<summary><b> Project 3: </b> Features of One Gender Schools (2021) </summary>
<a href= "https://larylc.github.io/Independent-Projects-/gendered_education_project_complete.html">Analyzed the key differences between co-ed colleges and single sex colleges.</a> 
</details>
<details>
<summary><b> Project 4: </b> Grandmaster B-days and B-places (2021) </summary>
<a href= "https://larylc.github.io/chess_bdays_bplaces/">Created original data set of chess grandmaster birth information using web-scraping tools and Wikipedia pages.</a> 
</details>

</div>

<div class= "dropdown dropdown2">
<button class= "drop-button">Minor Projects</button>
<details>
<summary><b> Minor Project 1:</b> Understanding Anime Genre Trends (2021) </summary>
<a href= "https://loganlary.shinyapps.io/anime1_030521/?_ga=2.199251374.1633841057.1615147342-569369622.1613318148">Examined popularity of anime genres. </a> 
</details>

<details>
<summary><b> Minor Project 2: </b> Do Children Have Bad Taste (2021) </summary>
<a href= "https://larylc.github.io/Independent-Projects-/tvanalysis.html">Explored how tv show ratings differ across age categories.</a> 
</details>

<details>
<summary><b> Minor Project 3: </b> Finding the Missing Records (2021) </summary>
<a href= "https://larylc.github.io/Independent-Projects-/missing_chess_records.html">Created original data set of chess grandmaster rating histories before the year 2000.</a> 
</details>
</div>


<div class= "dropdown dropdown3">
<button class= "drop-button">Data Visualizations</button>
<details>
<summary><b> Data Visualization App: </b> Pathway to Prodigy (2021) </summary>
<a href= "https://loganlary.shinyapps.io/prodigies_app/?_ga=2.15136438.103236738.1633010249-569369622.1613318148">Used original chess prodigy data set to create app that compares the rating trajectories of chess players over age ranges.</a> 
</details>

<details>
<summary><b> Data Visualization Website: </b> DreamWorks, Disney, or Pixar (2022) </summary>
<a href= "https://larylc.github.io/Independent-Projects-/dreamworks_disney_pixar.html">Used IMDB and Wikipedia data to analyze differences between animation studio movies.</a> 
</details>



<details>
<summary><b> Data Visualization Report: </b> Re-viz It (2022) </summary>
<a href= "https://larylc.github.io/Independent-Projects-/reviz_it.html">Redesigned old graphs using best data visualization best practices.</a> 
</details>

</div>
</div>
</div>









</div>
</div>


